### ISSUE TITLE
Logs arrived but are not displayed

### ISSUE THREAD

**Issue by santiagz** [wazuh/wazuh#10685]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.2.4| Rules/Decoders| Manager| Packages| Oracle Linux Server 8.4|

the problem is as follows:
I collect logs from the agent
```xml
<agent_config>
	<localfile>
		<location>/temp/honeypot_logs/log.json</location>
		<log_format>syslog</log_format>
	</localfile>
</agent_config>
```
getting them in `alerts.log` and `alerts.json` files:

 `alerts.json`
```json
{"timestamp":"2021-10-29T12:52:48.125+0300","rule":{"level":12,"description":"Honepots Event","id":"101006","firedtimes":1,"mail":true,"groups":["evian"," "]},"agent":{"id":"2936","name":"sb-hp-02","ip":"10.0.6.230"},"manager":{"name":"SB-WZ-04"},"id":"1635501168.4300094905","cluster":{"name":"wazuh-cluster-sb","node":"node04"},"full_log":"1 Oct-29-2021-09:52:47 ftp process HoneyPot:{\"ip\": \"0.0.0.0\", \"password\": \"test\", \"port\": 21, \"status\": \"success\", \"username\": \"test\"}","decoder":{"name":"hp-decoder"},"data":{"status":"success","ip":"0.0.0.0","password":"test","port":"21","username":"test"},"location":"/temp/honeypot_logs/log.json"}
```
 `alerts.log`
```
1 Oct-29-2021-08:44:19 ftp process HoneyPot:{"ip": "0.0.0.0", "password": "test", "port": 21, "status": "success", "username": "test"}
```
everything is processed by rules and decoders, 
![image](https://user-images.githubusercontent.com/72973604/139417396-22198e3b-8607-4346-90aa-4f67216ddf8f.png)

but not displayed in Security Events or Discovery at all.

I tried to change rules, decoders, change groups, change agents - but the logs in Wazuh are not displayed

my rule:
```xml
    <rule id="101006" level="12">
    <decoded_as>hp-decoder</decoded_as>
    <description>Honepots Event</description>
    </rule>
```
decoder
```xml
<decoder name="hp-decoder">
    <prematch>HoneyPot:</prematch>
    <plugin_decoder offset="after_prematch">JSON_Decoder</plugin_decoder>
</decoder>
```

**Comment by santiagz** [comment]
@JcabreraC  
i found the problem.

I tried to apply a new decoder for different kinds of rules, for a `localfile` and for a `syslog`, but result is the same

then I removed the plugin-line from the decoder
```xml
<plugin_decoder offset="after_prematch">JSON_Decoder</plugin_decoder>
```
and everything worked fine!

if I remove this line, the rule is displayed in `Security Events` and `Discovery`, 
and if i leave this line in decoder - doesn't show at all

at the same time, my old decoders work with this plugin so good, but new ones - do not

I think this happened after version 4.2.1, idk

**Comment by JcabreraC** [comment]
Hello santiagz,

I'm glad your problem has been solved.

I will investigate this behavior to see what is going on.

I am closing this issue, If you have any questions, you can also use our Slack channel or subscribe to our mailing list.

Best regards,
Juan

**Comment by santiagz** [comment]
hi @JcabreraC 
unfortunately my problem was not solved :( 
I just found the reason.
