### ISSUE TITLE
Cannot find '/queue/db/wdb'

### ISSUE THREAD

**Issue by kingtedd** [wazuh/wazuh#11854]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | Wazuh Database | Manager | Sources | RHEL 8.4 |

Hi,

After configured DB output and restart , i got this log

2022/01/19 02:59:00 wazuh-analysisd[3437978] analysisd.c:740 at main(): INFO: Total rules enabled: '3882'
2022/01/19 02:59:00 wazuh-analysisd[3437978] analysisd.c:811 at main(): INFO: Started (pid: 3437978).
**2022/01/19 02:59:00 wazuh-analysisd[3437978] wazuhdb_op.c:32 at wdbc_connect(): INFO: Cannot find 'queue/db/wdb'. Waiting 1 seconds to reconnect.**
2022/01/19 02:59:00 wazuh-analysisd[3437978] asyscom.c:173 at asyscom_main(): DEBUG: Local requests thread ready
2022/01/19 02:59:01 wazuh-analysisd[3437978] wazuhdb_op.c:32 at wdbc_connect(): INFO: Cannot find 'queue/db/wdb'. Waiting 2 seconds to reconnect.
2022/01/19 02:59:03 wazuh-analysisd[3437978] wazuhdb_op.c:32 at wdbc_connect(): INFO: Cannot find 'queue/db/wdb'. Waiting 3 seconds to reconnect.
2022/01/19 02:59:06 wazuh-analysisd[3437978] wazuhdb_op.c:41 at wdbc_connect(): ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/01/19 02:59:06 wazuh-analysisd[3437978] wazuhdb_op.c:123 at wdbc_query_ex(): ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/01/19 02:59:06 wazuh-analysisd[3437978] wazuhdb_op.c:211 at wdbc_query_parse_json(): ERROR: Unable to connect to socket 'queue/db/wdb'
2022/01/19 02:59:06 wazuh-analysisd[3437978] mitre.c:46 at mitre_load(): ERROR: Response from the Mitre database cannot be parsed.
2022/01/19 02:59:06 wazuh-analysisd[3437978] mitre.c:155 at mitre_load(): ERROR: Mitre matrix information could not be loaded.
2022/01/19 02:59:06 wazuh-analysisd[3437978] rootcheck.c:40 at RootcheckInit(): DEBUG: RootcheckInit completed.
2022/01/19 02:59:06 wazuh-analysisd[3437978] syscollector.c:211 at SyscollectorInit(): DEBUG: SyscollectorInit completed.
2022/01/19 02:59:06 wazuh-analysisd[3437978] ciscat.c:35 at CiscatInit(): DEBUG: CiscatInit completed.
2022/01/19 02:59:06 wazuh-analysisd[3437978] winevtchannel.c:47 at WinevtInit(): DEBUG: WinevtInit completed.
2022/01/19 02:59:06 wazuh-analysisd[3437978] security_configuration_assessment.c:84 at SecurityConfigurationAssessmentInit(): DEBUG: SecurityConfigurationAssessmentInit completed.
2022/01/19 02:59:06 wazuh-analysisd[3437978] accumulator.c:92 at Accumulate_Init(): DEBUG: Accumulator Init completed.
2022/01/19 02:59:06 wazuh-analysisd[3437978] analysisd.c:919 at OS_ReadMSG(): DEBUG: Active response Init completed.
2022/01/19 02:59:06 wazuh-analysisd[3437978] analysisd.c:1004 at OS_ReadMSG(): DEBUG: FTS_Init completed.
2022/01/19 02:59:06 wazuh-analysisd[3437978] analysisd.c:1179 at ad_input_main(): DEBUG: Input message handler thread started.
2022/01/19 02:59:06 wazuh-analysisd[3437978] analysisd.c:1078 at OS_ReadMSG(): DEBUG: Startup completed. Waiting for new messages..
2022/01/19 02:59:06 wazuh-analysisd[3437978] state.c:86 at w_analysisd_state_main(): DEBUG: State file updating thread started.
2022/01/19 02:59:06 wazuh-analysisd[3437978] logtest.c:49 at w_logtest_init(): INFO: (7200): Logtest started

i checked on /var/ossec/queue/db, there is no wdb file

anyone have a clue or solution? 
thx,

**Comment by vikman90** [comment]
Hi @kingtedd,

This issue is a consequence of #10690 which has been fixed by #10849 for the upcoming version 4.3.0. The cause is that the script that starts and stops the Wazuh daemon is confusing `wazuh-dbd` (the DB output) and `wazuh-db` (the internal database). As `wazuh-db` is not starting, Analysisd is unable to connect to it.

Some workarounds are:

- Handle Wazuh DB manually:
```sh
service wazuh-manager start
/var/ossec/bin/wazuh-db
```
- Copy [wazuh-server.sh](https://github.com/wazuh/wazuh/blob/4.3/src/init/wazuh-server.sh) from sources version 4.3 into _/var/ossec/bin/wazuh-control_. Keep lines 16 and 17 from [v4.2.5](https://github.com/wazuh/wazuh/blob/v4.2.5/src/init/wazuh-server.sh#L16-L17), which indicate the manager version.

Hope this helps you. Let me close this issue as the cause is already fixed. Feel free to reopen it if you have any questions.

Best regards.

**Comment by ketantande** [comment]
> Hi @kingtedd,
> 
> This issue is a consequence of #10690 which has been fixed by #10849 for the upcoming version 4.3.0. The cause is that the script that starts and stops the Wazuh daemon is confusing `wazuh-dbd` (the DB output) and `wazuh-db` (the internal database). As `wazuh-db` is not starting, Analysisd is unable to connect to it.
> 
> Some workarounds are:
> 
> * Handle Wazuh DB manually:
> 
> ```shell
> service wazuh-manager start
> /var/ossec/bin/wazuh-db
> ```
> 
> * Copy [wazuh-server.sh](https://github.com/wazuh/wazuh/blob/4.3/src/init/wazuh-server.sh) from sources version 4.3 into _/var/ossec/bin/wazuh-control_. Keep lines 16 and 17 from [v4.2.5](https://github.com/wazuh/wazuh/blob/v4.2.5/src/init/wazuh-server.sh#L16-L17), which indicate the manager version.
> 
> Hope this helps you. Let me close this issue as the cause is already fixed. Feel free to reopen it if you have any questions.
> 
> Best regards.


Hello Vikman

I am also facing the same error also I tried the solution provided by you in above comment but still facing the same issue.

Please help me to resolve this issue.

**Comment by vikman90** [comment]
Hi @ketantande,

The solution I provided aims to fix the following problem:

```sh
# service wazuh-manager stop
# /var/ossec/bin/wazuh-control start
Starting Wazuh v4.2.5...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
wazuh-db already running...
^^^^^^^^^^^^^^^^^^^^^^^^^^^
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.
```

As the name of the daemon `wazuh-dbd` (database output) starts with "wazuh-db", the `wazuh-control` script wrongly detects that the daemon `wazuh-db` (agent inventory database manager) is already running, because `wazuh-dbd` had started just before. Then, we find these errors in the log:

```
2022/02/16 14:15:05 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/02/16 14:15:03 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
```

By replacing `wazuh-control` with [its source at 4.3](https://github.com/wazuh/wazuh/blob/4.3/src/init/wazuh-server.sh), the script will no longer confuse `wazuh-db` and `wazuh-dbd`. Just to confirm, this is only possible if the [database output](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/database-output.html) is enabled.

After the fix, `wazuh-control` should behave this way:
```sh
# /var/ossec/bin/wazuh-control stop
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
wazuh-db not running...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
Killing wazuh-dbd...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.2.5 Stopped

# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd is running...
wazuh-csyslogd not running...
wazuh-apid is running...
```

When you replace the script, please ensure that no Wazuh daemons are running:
```sh
/var/ossec/bin/wazuh-control stop
ps aux | grep "wazuh-"
```

After doing this, you should be able to start the service normally:
```sh
service wazuh-manager start
```

And no errors related to the `wdb` socket should appear in the log.

Please confirm that you followed these steps, and you have set up `<database_output>`. Otherwise, the problem you are having may be due to another cause.

Best regards.

**Comment by ketantande** [comment]
> database_output

Hello vikman90,

Thanks for quick reply

we have not setup <database_output> in our setup but still facing mentioned problem. Please let us know if you need any further details to understand issue.

**Comment by ketantande** [comment]
When i am executing wazuh control ass mentioned in your solution i am getting error "wazuh-db did not start correctly."

 /var/ossec/bin/wazuh-control start
Starting Wazuh v4.2.5...
wazuh-apid: Process 3960 not used by Wazuh, removing...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/02/16 14:47:58 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
wazuh-authd already running...
wazuh-db did not start correctly.

**Comment by ketantande** [comment]
> When i am executing wazuh control ass mentioned in your solution i am getting error "wazuh-db did not start correctly."
> 
> /var/ossec/bin/wazuh-control start Starting Wazuh v4.2.5... wazuh-apid: Process 3960 not used by Wazuh, removing... Started wazuh-apid... Started wazuh-csyslogd... Started wazuh-dbd... 2022/02/16 14:47:58 wazuh-integratord: INFO: Remote integrations not configured. Clean exit. Started wazuh-integratord... Started wazuh-agentlessd... wazuh-authd already running... wazuh-db did not start correctly.

Just to update on issue 

This reported issue started when we were trying to forward wazuh logs to our SIEM server (We are only using Wazuh for FIM)
So We added below strings in ossec.cong file and saved the changes and after that restarted Wazuh-manager server
from that time we are facing above error, so we had reverted all the changes but still we are getting reported error <ossec_config>
<syslog_output>
    <server>x.x.x.x</server>
</syslog_output>
</ossec_config>

Ref : https://documentation.wazuh.com/current/user-manual/manager/manual-syslog-output.html

I have tried to run wazuh-control commmand as advised by you and getting below result.

:/var/ossec/bin# sh wazuh-control restart
wazuh-clusterd not running...
wazuh-modulesd not running...
wazuh-monitord not running...
wazuh-logcollector not running...
wazuh-remoted not running...
wazuh-syscheckd not running...
wazuh-analysisd not running...
wazuh-maild not running...
wazuh-execd not running...
wazuh-db not running...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.2.5 Stopped
Starting Wazuh v4.2.5...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/02/17 04:38:53 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
wazuh-db did not start correctly.

**Comment by vikman90** [comment]
@ketantande I'm afraid that the cause of this problem is a different one. In this case, `wazuh-control` is trying to launch `wazuh-db` (which creates the database server at _queue/db/wdb_).

Wazuh DB is failing to start. The most common cause is that the internal configuration files (_etc/internal_options.conf_ and _etc/local_internal_options.conf_) have an invalid format or a wrong value.

The log should help us out:
```sh
grep "wazuh-db[:\[]" /var/ossec/logs/ossec.log
```

Otherwise, try to manually run Wazuh DB. If we set an invalid value, like:
```sh
echo "wazuh_db.open_db_limit=0" >> /var/ossec/etc/local_internal_options.conf
```

This is what we expect (run Wazuh DB with option `-d` to enable debugging logs):
```
# /var/ossec/bin/wazuh-db -d
2022/02/17 17:11:02 wazuh-db[14546] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/02/17 17:11:02 wazuh-db[14546] validate_op.c:230 at getDefine_Int(): CRITICAL: (2302): Invalid definition for wazuh_db.open_db_limit: '0'.

# echo $?
1
```

That error code (`1`) is what makes `wazuh-control` print "wazuh-db did not start correctly."

It you get an error different than an invalid configuration, and you need further help to fix it, I would kindly ask you to open a new issue as this is a different problem yet having a similar error log.

Thank you for reporting this.
Best regards.

**Comment by vikman90** [comment]
As I see this issue is being addressed at #12320. Let me close this ticket.

**Comment by ketantande** [comment]
Hello vikman90,

Reported issue has been resolved by changing permission of ossec.conf file.

Thanks for prompt support.
