### ISSUE TITLE
NO data show Security events , integrity monitoring , policy monitoring

### ISSUE THREAD

**Issue by arielravi** [wazuh/wazuh#1244]
I have 2 active agents Windows , and Linux .I am testing wazuh 
When I click overview and select This month I don't see any data
There are no results for selected time range. Try another one.
I got this response:
There are no results for selected time range. Try another one.
BTW , If I click on Discover , This month , on 
Wazuh-alerts-3.0 No results match your search criteria

**Comment by arielravi** [comment]
here is logs from wazuhapp.log
{"date":"2018-09-05T00:00:01.038Z","level":"info","location":"[monitoring][createIndex]","message":"Successfully created today index."}
{"date":"2018-09-05T21:16:55.980Z","level":"info","location":"[initialize]","message":"Kibana index: .kibana"}
{"date":"2018-09-05T21:16:55.982Z","level":"info","location":"[initialize]","message":"App revision: 0407"}
{"date":"2018-09-05T21:16:55.982Z","level":"info","location":"[monitoring][configuration]","message":"wazuh.monitoring.enabled: true"}
{"date":"2018-09-05T21:16:55.982Z","level":"info","location":"[monitoring][configuration]","message":"wazuh.monitoring.frequency: 3600 (0 */60 * * * *) "}
{"date":"2018-09-05T21:16:55.982Z","level":"info","location":"[monitoring][checkKibanaStatus]","message":"Waiting for Kibana and Elasticsearch servers to be ready..."}
{"date":"2018-09-05T21:16:57.581Z","level":"info","location":"[monitoring][init]","message":"Creating/Updating wazuh-agent template..."}
{"date":"2018-09-05T21:16:57.582Z","level":"info","location":"[monitoring][checkTemplate]","message":"Updating wazuh-monitoring template..."}
{"date":"2018-09-05T21:16:57.605Z","level":"info","location":"[initialize][checkWazuhIndex]","message":"Checking .wazuh index."}
{"date":"2018-09-05T21:16:57.605Z","level":"info","location":"[initialize][checkWazuhVersionIndex]","message":"Checking .wazuh-version index."}
{"date":"2018-09-05T21:16:57.728Z","level":"info","location":"[initialize][checkKnownFields]","message":"x-pack enabled: no"}
{"date":"2018-09-05T21:16:57.842Z","level":"info","location":"[monitoring][init]","message":"Creating today index..."}
{"date":"2018-09-05T21:16:57.844Z","level":"info","location":"[initialize][checkAPIEntriesExtensions]","message":"Checking extensions consistency for all API entries"}
{"date":"2018-09-05T21:16:57.865Z","level":"info","location":"[initialize][checkKnownFields]","message":"Found 2 index patterns"}
{"date":"2018-09-05T21:16:57.866Z","level":"info","location":"[initialize][checkKnownFields]","message":"Found 1 valid index patterns for Wazuh alerts"}
{"date":"2018-09-05T21:16:57.866Z","level":"info","location":"[initialize][checkKnownFields]","message":"Default index pattern found"}
{"date":"2018-09-05T21:16:57.866Z","level":"info","location":"[initialize][checkKnownFields]","message":"Refreshing known fields for \"index-pattern:wazuh-alerts-3.x-*\""}
{"date":"2018-09-05T21:16:57.901Z","level":"info","location":"[initialize][checkAPIEntriesExtensions]","message":"Successfully updated API entry extensions with ID: 1535997709523"}
{"date":"2018-09-05T21:16:57.931Z","level":"info","location":"[initialize][checkKnownFields]","message":"App ready to be used."}
{"date":"2018-09-05T21:16:57.944Z","level":"info","location":"[monitoring][init]","message":"Checking if wazuh-monitoring pattern exists..."}
{"date":"2018-09-05T21:16:57.959Z","level":"info","location":"[monitoring][init]","message":"Skipping wazuh-monitoring pattern creation. Already exists."}
{"date":"2018-09-06T00:00:01.068Z","level":"info","location":"[monitoring][createIndex]","message":"Successfully created today index."}
{"date":"2018-09-06T14:12:37.852Z","level":"error","location":"GET /refresh-fields/{pattern}","message":"Not Found"}

**Comment by arielravi** [comment]
I was following data flow
I found a issue from filebeat to logstash . I am verify configuration

**Comment by arielravi** [comment]
I was able to make work . I fixed working with filebeat and logstash configuration
Any guide to setup SSL for filebeat logstash ?

**Comment by JuanjiJG** [comment]
Hello @arielravi,

Yes, the most common cause when your app doesn't have any events to show is that there's a problem on the data flow between the Wazuh manager and Elasticsearch. In this case, it seems like you had issues between Filebeat and Logstash.

We do have a guide in our documentation to configure SSL between Filebeat and Logstash. You can check it [here](https://documentation.wazuh.com/current/installation-guide/optional-configurations/elastic_ssl.html).

Let us know if you have more problems or questions about this.

Regards,
Juanjo

**Comment by bah07** [comment]
Hi @arielravi 

We will proceed to close the issue. Please reopen it in case you need more information or are still having problems. 

Regards.
