### ISSUE TITLE
Duplicate agent IDs prevent sending logs to server

### ISSUE THREAD

**Issue by copacetic** [wazuh/wazuh#159]
When I register agents, sometimes I'll get duplicate ID's. For instance, when an agent registers, it might get the ID 003, even if a different agent already had that ID. It seems that some of the agents fail to connect when there is a duplicate ID. I'm running the authd like so:
`sudo /var/ossec/bin/ossec-authd -r -v /var/ossec/etc/rootCA.pem -x /var/ossec/etc/sslmanager.cert -k /var/ossec/etc/sslmanager.key`

I am pretty confused. The logs on the agent with the duplicate ID show the following:
```
...repeated...
2017/07/24 16:32:38 ossec-agentd: INFO: Trying to connect to server (server_ip).
2017/07/24 16:32:59 ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: 'server_ip'.
2017/07/24 16:43:00 ossec-agentd: INFO: Trying to connect to server (server_ip).
2017/07/24 16:43:21 ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: 'server_ip'.
...repeated...
```

**Comment by vikman90** [comment]
Hi @copacetic,

Wazuh shouldn't give the same ID twice, unless option `-r` is present.

The default behavior when deleting an agent, either manually or auto-deletion due to duplicated IP (option `-f`) is to mark the removed agent with a `!` symbol in the file `client.keys`, so the agent is deleted but the ID is present to prevent other agents from being assigned the same ID.

Option `-r` purges those removed agents from the `client.keys` file. This implies that `ossec-authd` may assign an old ID. Please give a try removing option `-r` and tell us if this solves the issue.

Anyway I'd like to know if the manager's log shows an error when an agent with duplicated ID tries to connect.

Thank you for feedback.
Best regards.

**Comment by copacetic** [comment]
Hi Vikman,

The manager's log does not show an error. I think it's worth adding one, since I spent significant time looking at firewall rules instead.

I had to add the `-r` to avoid the segfault in #148. I guess now that it's probably resolved I can try again. Has the Debian package been updated with your fix, or will I need to build a more up-to-date Debian package myself? 

Thank you,
Hayg

**Comment by copacetic** [comment]
I confirmed #148 is still an issue for your hosted Debian package. I'm basically stuck between two bugs. One is that Authd will segfault if I run it with standard arguments, the other is that it will create duplicate ID's and quietly block agents with duplicate ID's. Vikman, what do you think I should do?

**Comment by vikman90** [comment]
Hi,

we have released Wazuh v2.0.1 a few hours ago. You should be able to upgrade your version 2.0 by _apt-get_.

Please tell us if you have any issue with this.
Best regards.

**Comment by copacetic** [comment]
@vikman90 unfortunately this is still an issue for me, even after removing `-r`.
```
hayg@wazuh-server:~$ sudo cat /var/ossec/etc/client.keys
002 162.com any xxx
003 64.com any xxx
004 333.com any xxx
005 284.com any xxx
006 299.com2 any xxx
001 161.com any xxx
002 359.com any xxx
001 !299.com any xxx```
notice the duplicate 002. This is after I deleted the client.keys and went about re-enrolling many machines. I also had upgraded the package to fix the segfault. All help appreciated.

**Comment by vikman90** [comment]
Hi @copaceptic,

we are trying to reproduce this issue. Could you tell us which operating system, architecture and Wazuh version are you using, please? We appreciate if you told us which steps you follow to reproduce this problem.

Thanks in advance.
Best regards.

**Comment by copacetic** [comment]
Hi @vikman90,

This is on Debian Wheezy running the latest wazuh manager package from your Debian repo. Here is the dpkg info:
`wazuh-manager                      2.0.1-2wheezy                       i386`

The architecture:
64 bit kernel, but runs multiarch userspace in both 32 bit and 64 bit. 
```
$ uname -m
x86_64
$ dpkg --print-architecture
i386
$dpkg --print-foreign-architectures
amd64
```

As always, thank you.
Hayg

**Comment by copacetic** [comment]
I definitely restart ossec quite often. Is all the ID state stored in `client.keys`? Should I be deleting `/var/ossec` on the agents when re-enrolling? Could it be that since I didn't clear `client.keys` on the agent, it is using the ID from its previous enrollment with the server, even if I delete `client.keys` on the server?

**Comment by vikman90** [comment]
Hi,

we confirmed that there is a bug that only affects to i686 architecture: Authd always assigns new agents starting by 001 no matter the content of the `client.keys`.

Please let me work on it and find the problem. Maybe it is related to issue https://github.com/wazuh/wazuh/issues/148.

I'll keep you informed.
Best regards.

**Comment by copacetic** [comment]
Aha. Sounds good. Thanks.

**Comment by copacetic** [comment]
Yeah. It seems after a restart it begins at ID 0 again.

**Comment by vikman90** [comment]
Hi @copacetic,

I think I've fixed it: https://github.com/wazuh/wazuh/commit/386ebbde016ca236c2ffa6170f6417249d54996b.

Including `<time.h>` before `"shared.h"` produced the same problem that last time. Due to this, the ID counter, used to assign new agent IDs, was not read properly.

This fix arrives just in time for the v2.1.0!  Please test it and tell us if it's working properly.

You helped us to catch another bug. Thank you very much!
Best regards.

**Comment by copacetic** [comment]
Hi @vikman90,

Great! Mind doing a Debian release so I can test easily? :)

Thanks,
Hayg

**Comment by vikman90** [comment]
Hi @copacetic,

yes, we are preparing the version 2.1.0 and plan to release it in few days.

Regards.

**Comment by copacetic** [comment]
Alrighty.

**Comment by vikman90** [comment]
Hi James,

we released Wazuh v2.1 yesterday. I hope this new version fixes all the problems that you reported.

Let me close this issue.
Regards.

**Comment by copacetic** [comment]
Hi vikman90,

Thanks for letting me know and for fixing / releasing. 

Best,
Hayg
