### ISSUE TITLE
Azure auditLogs/signIns Not Showing as an Alert in the Dashboard

### ISSUE THREAD

**Issue by liam-silvatech** [wazuh/wazuh#16002]
It's affecting the signIn logs for me. I can see in the alerts.json the sign in event, with all the data perfectly.

But running a ruleset test and pasting in that data comes up with on phase 3.

```
**Phase 3: Completed filtering (rules).
	id: '1002'
	level: '2'
	description: 'Unknown problem somewhere in the system.'
	groups: '["syslog","errors"]'
	firedtimes: '1'
	gpg13: '["4.3"]'
	mail: 'false'
```
Data is decoded fine.

I've only just started to learn Wazuh, but in the rule it has this;

```
<rule id="87802" level="3">
    <decoded_as>json</decoded_as>
    <field name="azure_tag">azure-ad-graph</field>
    <description>Azure: AD $(activity)</description>
</rule>
```
Will it error because `activity` doesn't exist? Only think this because `auditLogs/directoryAudits` works as expected. So is `auditLogs/signIns` failing because a rule is expecting the format of a directory audit?

_Originally posted by @liam-silvatech in https://github.com/wazuh/wazuh/issues/15633#issuecomment-1402818006_

**Comment by liam-silvatech** [comment]
To be clear this is using the Microsoft Graph approach.

I added these 2 rules as a test but still no luck.

I can see the signins have successfully been downloaded into `/var/ossec/logs/alerts/alerts.json` but seems to stop there. What am I missing? Any ideas.

Rules I made for testing.

```
  <rule id="87814" level="3">
    <decoded_as>json</decoded_as>
    <field name="isInteractive">true</field>
    <description>Azure: AD Interactive SignIn</description>
    <options>no_full_log</options>
  </rule>

  <rule id="87815" level="3">
    <decoded_as>json</decoded_as>
    <field name="isInteractive">false</field>
    <description>Azure: AD Non-Interactive SignIn</description>
    <options>no_full_log</options>
  </rule>
  ```

**Comment by liam-silvatech** [comment]
My `/var/ossec/etc/ossec.conf` file config:

```
<wodle name="azure-logs">

    <disabled>no</disabled>
    <interval>1h</interval>
    <run_on_start>yes</run_on_start>

    <graph>

        <auth_path>/var/ossec/wodles/azure/credentials</auth_path>
        <tenantdomain>SomeTenant.onmicrosoft.com</tenantdomain>

        <request>
            <tag>azure-active_directory</tag>
            <query>auditLogs/signIns</query>
            <time_offset>1h</time_offset>
        </request>
        <request>
            <tag>azure-active_directory-silvatech</tag>
            <query>auditLogs/directoryAudits</query>
            <time_offset>1h</time_offset>
        </request>
    </graph>

</wodle>
```

**Comment by jnasselle** [comment]
Hi @liam-silvatech ,

As far as I can understand, you are trying to create a custom rule based on the default ones [(87801 to 87813)
](https://github.com/wazuh/wazuh/blob/v4.3.10/ruleset/rules/0555-azure_rules.xml)

Logs evaluation is like a tree: once the log matches one rule, it will continue with their child's rules. So, you need to chain your new custom rule (BTW is recommended to use id between 100000 and 120000 to custom rules) to one that already matches your log. In your case will be `87802`, and adding as an extra condition to check the `interactive` field

```xml
  <rule id="100001" level="3">
    <if_sid>87802</if_sid>
    <field name="isInteractive">true</field>
    <description>Azure: AD Interactive SignIn</description>
    <options>no_full_log</options>
  </rule>
```

**Comment by liam-silvatech** [comment]
hi @jnasselle 

I have confused things my custom rules was testing to see if it was working, you are right I completely didn't read the docs.

My actual issue though is that all of the MS graph requests to `auditLogs/signIns` get ingested into alerts.json I can see the raw result perfectly in there. But it does not create a security event, thus I have no ability to alert on failed or successful logins.

To repeat create yourself an application in Azure as per the docs, use the MS graph request to `auditLogs/signIns` as per the docs. Then restart manager, you will then see the alerts.json is filling up with all the signin information but nothing is displayed in the dashboard.

I don't know wazuh well enough to diagnose further, it's a fresh wazuh build and the first thing I did is add the `auditLogs/signIns` as that's all I want it to do for now. Not sure what I am missing.

**Comment by jnasselle** [comment]
Hi @liam-silvatech ,

So you are being able to get your alerts into alerts.json but not to Wazuh Dashboard? seems to be something related to the Wazuh Indexer ingestion template.

Could you please share an alert that is currently having this problem? Please obfuscate sensitive information but keep the alert structure to check it.

**Comment by liam-silvatech** [comment]
```
{
  "timestamp": "2023-01-27T20:59:23.405+0000",
  "rule": {
    "level": 3,
    "description": "Azure: AD ",
    "id": "87802",
    "firedtimes": 5,
    "mail": false,
    "groups": [
      "azure"
    ]
  },
  "agent": {
    "id": "000",
    "name": "wazuh"
  },
  "manager": {
    "name": "wazuh"
  },
  "id": "1674853163.269717",
  "decoder": {
    "name": "json"
  },
  "data": {
    "id": "00000000-0000-0000-0000-000000000000",
    "createdDateTime": "2023-01-27T20:48:11Z",
    "userDisplayName": "First Second",
    "userPrincipalName": "first.second@contoso.com",
    "userId": "00000000-0000-0000-0000-000000000000",
    "appId": "00000000-0000-0000-0000-000000000000",
    "appDisplayName": "Some Microsoft Application",
    "ipAddress": "123.123.123.123",
    "clientAppUsed": "Browser",
    "correlationId": "00000000-0000-0000-0000-000000000000",
    "conditionalAccessStatus": "success",
    "isInteractive": "true",
    "riskDetail": "hidden",
    "riskLevelAggregated": "hidden",
    "riskLevelDuringSignIn": "hidden",
    "riskState": "none",
    "riskEventTypes": [],
    "riskEventTypes_v2": [],
    "resourceDisplayName": "Microsoft Graph",
    "resourceId": "00000003-0000-0000-c000-000000000000",
    "status": {
      "errorCode": "0",
      "failureReason": "Other.",
      "additionalDetails": "MFA requirement satisfied by claim in the token"
    },
    "deviceDetail": {
      "deviceId": "00000000-0000-0000-0000-000000000000",
      "displayName": "SOME-HOSTNAME",
      "operatingSystem": "Windows 95",
      "browser": "Netscape 1.1.1",
      "isCompliant": "true",
      "isManaged": "true",
      "trustType": "Azure AD joined"
    },
    "location": {
      "city": "Not",
      "state": "Real",
      "countryOrRegion": "GB",
      "geoCoordinates": {
        "altitude": "null",
        "latitude": "12.345678",
        "longitude": "-12.345678"
      }
    },
    "appliedConditionalAccessPolicies": [],
    "azure_tag": "azure-ad-graph",
    "azure_aad_tag": "azure-active_directory"
  },
  "location": "Azure"
}
```

Here is an example, a couple of hours ago, but not shown within the dashboard.

**Comment by liam-silvatech** [comment]
The description of `Azure: AD ` is correct as there is no activity to populate the last half as per your rule 87802.

**Comment by jnasselle** [comment]
Hi @liam-silvatech ,

I have tested your log and, as you mentioned, it is generating an error during its ingestion by Filebeat (/var/log/filebeat).

```
2023-01-30T12:23:53.417Z	WARN	[elasticsearch]	elasticsearch/client.go:408	Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xc0ee0b96171b021b, ext:203393235857, loc:(*time.Location)(0x42417a0)}, Meta:{"pipeline":"filebeat-7.10.2-wazuh-alerts-pipeline"}, Fields:{"agent":{"ephemeral_id":"31ba29fd-0e36-4d02-bb4c-52f8eb65bb95","hostname":"wazuh-server","id":"6b61d7f2-fe9e-4ef2-838c-7077d0b427fd","name":"wazuh-server","type":"filebeat","version":"7.10.2"},"ecs":{"version":"1.6.0"},"event":{"dataset":"wazuh.alerts","module":"wazuh"},"fields":{"index_prefix":"wazuh-alerts-4.x-"},"fileset":{"name":"alerts"},"host":{"name":"wazuh-server"},"input":{"type":"log"},"log":{"file":{"path":"/var/ossec/logs/alerts/alerts.json"},"offset":18182},"message":"{\"timestamp\":\"2023-01-27T20:59:23.405+0000\",\"rule\":{\"level\":3,\"description\":\"Azure: AD \",\"id\":\"87802\",\"firedtimes\":5,\"mail\":false,\"groups\":[\"azure\"]},\"agent\":{\"id\":\"000\",\"name\":\"wazuh\"},\"manager\":{\"name\":\"wazuh\"},\"id\":\"1674853163.269717\",\"decoder\":{\"name\":\"json\"},\"data\":{\"id\":\"00000000-0000-0000-0000-000000000000\",\"createdDateTime\":\"2023-01-27T20:48:11Z\",\"userDisplayName\":\"First Second\",\"userPrincipalName\":\"first.second@contoso.com\",\"userId\":\"00000000-0000-0000-0000-000000000000\",\"appId\":\"00000000-0000-0000-0000-000000000000\",\"appDisplayName\":\"Some Microsoft Application\",\"ipAddress\":\"123.123.123.123\",\"clientAppUsed\":\"Browser\",\"correlationId\":\"00000000-0000-0000-0000-000000000000\",\"conditionalAccessStatus\":\"success\",\"isInteractive\":\"true\",\"riskDetail\":\"hidden\",\"riskLevelAggregated\":\"hidden\",\"riskLevelDuringSignIn\":\"hidden\",\"riskState\":\"none\",\"riskEventTypes\":[],\"riskEventTypes_v2\":[],\"resourceDisplayName\":\"Microsoft Graph\",\"resourceId\":\"00000003-0000-0000-c000-000000000000\",\"status\":{\"errorCode\":\"0\",\"failureReason\":\"Other.\",\"additionalDetails\":\"MFA requirement satisfied by claim in the token\"},\"deviceDetail\":{\"deviceId\":\"00000000-0000-0000-0000-000000000000\",\"displayName\":\"SOME-HOSTNAME\",\"operatingSystem\":\"Windows 95\",\"browser\":\"Netscape 1.1.1\",\"isCompliant\":\"true\",\"isManaged\":\"true\",\"trustType\":\"Azure AD joined\"},\"location\":{\"city\":\"Not\",\"state\":\"Real\",\"countryOrRegion\":\"GB\",\"geoCoordinates\":{\"altitude\":\"null\",\"latitude\":\"12.345678\",\"longitude\":\"-12.345678\"}},\"appliedConditionalAccessPolicies\":[],\"azure_tag\":\"azure-ad-graph\",\"azure_aad_tag\":\"azure-active_directory\"},\"location\":\"Azure\"}","service":{"type":"wazuh"}}, Private:file.State{Id:"native::68703103-2049", PrevId:"", Finished:false, Fileinfo:(*os.fileStat)(0xc000551930), Source:"/var/ossec/logs/alerts/alerts.json", Offset:19795, Timestamp:time.Time{wall:0xc0ee0b6853b7d245, ext:20336403899, loc:(*time.Location)(0x42417a0)}, TTL:-1, Type:"log", Meta:map[string]string(nil), FileStateOS:file.StateOS{Inode:0x418537f, Device:0x801}, IdentifierName:"native"}, TimeSeries:false}, Flags:0x1, Cache:publisher.EventCache{m:common.MapStr(nil)}} (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse field [data.status] of type [keyword] in document with id '_VaiAoYBjHTPWPxPQdFC'. Preview of field's value: '{failureReason=Other., errorCode=0, additionalDetails=MFA requirement satisfied by claim in the token}'","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:1280"}}
```
The error is because the `status` field is not expected to be a JSON object. Here's the description https://github.com/wazuh/wazuh/blob/v4.3.10/extensions/elasticsearch/7.x/wazuh-template.json#L1017-L1019

I'm going to add this issue to https://github.com/wazuh/wazuh/issues/9949 to track this kind of errors

**Comment by tdtmusic2** [comment]
Hello everyone. I have the exact same issue, fresh installation of Wazuh via script. Logs are present in alerts.json but nothing in the web interface. Same errors as the OP.

**Comment by Selutario** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/22392. Thank you for your contribution @jmnis and @fdalmaup.

**Comment by joshhcd** [comment]
I've been trying to implement this change in my 4.8 release. I made the adjustments mentioned in #22392 and then restarted, but the logs are still not being ingested. any ideas?
