### ISSUE TITLE
The email a syscheck alert doesn't contain the diff 

### ISSUE THREAD

**Issue by jlruizmlg** [wazuh/wazuh#163]
When Syscheck has the option ```report_changes="yes"```  over a folder, the email alert doesn't show the changes, but in the alerts.json and alerts.log works.

Alerts.json

```
{"timestamp":"2017-08-04T04:51:00-0500","rule":{"level":7,"description":"Integrity checksum changed.","id":"550","firedtimes":2,"mail":true,"groups":["ossec","syscheck"],"pci_dss":["11.5"]},"agent":{"id":"000","name":"manager"},"manager":{"name":"manager"},"full_log":"Integrity checksum changed for: '/home/test_wazuh'\nSize changed from '0' to '28'\nOld md5sum was: 'd41d8cd98f00b204e9800998ecf8427e'\nNew md5sum is : 'ead0af83ad49de33db724806aa562a36'\nOld sha1sum was: 'da39a3ee5e6b4b0d3255bfef95601890afd80709'\nNew sha1sum is : '8a826b0c3466fd2a6764d338d29298a39ca60ca1'\n","syscheck":{"path":"/home/test_wazuh","size_before":"0","size_after":"28","perm_after":"100644","uid_after":"0","gid_after":"0","md5_before":"d41d8cd98f00b204e9800998ecf8427e","md5_after":"ead0af83ad49de33db724806aa562a36","sha1_before":"da39a3ee5e6b4b0d3255bfef95601890afd80709","sha1_after":"8a826b0c3466fd2a6764d338d29298a39ca60ca1","uname_after":"root","gname_after":"root","mtime_before":"2017-08-04T04:50:45","mtime_after":"2017-08-04T04:50:54","inode_before":50816999,"inode_after":50850806,"diff":"0a1\n> this is a test for syscheck\n","event":"modified"},"decoder":{"name":"syscheck_integrity_changed"},"hostname":"manager","location":"syscheck"}
```

Alerts.log

```
File: /home/test_wazuh
Old size: 0
New size: 28
New permissions: 100644
New user: root (0)
New group: root (0)
Old MD5: d41d8cd98f00b204e9800998ecf8427e
New MD5: ead0af83ad49de33db724806aa562a36
Old SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
New SHA1: 8a826b0c3466fd2a6764d338d29298a39ca60ca1
Old date: Fri Aug  4 04:50:45 2017
New date: Fri Aug  4 04:50:54 2017
Old inode: 50816999
New inode: 50850806
What changed: 0a1
> this is a test for syscheck


```

Email

```

Wazuh Notification. 
2017 Aug 04 04:50:55 

Received From: manager->syscheck 
Rule: 553 fired (level 7) -> "File deleted. Unable to retrieve checksum." 
Portion of the log(s): 

File '/home/.test_wazuh.swp' was deleted. Unable to retrieve checksum. 
File: /home/.test_wazuh.swp 



--END OF NOTIFICATION 



Wazuh Notification. 
2017 Aug 04 04:51:00 

Received From: manager->syscheck 
Rule: 550 fired (level 7) -> "Integrity checksum changed." 
Portion of the log(s): 

Integrity checksum changed for: '/home/test_wazuh' 
Old md5sum was: 'd41d8cd98f00b204e9800998ecf8427e' 
New md5sum is : 'ead0af83ad49de33db724806aa562a36' 
Old sha1sum was: 'da39a3ee5e6b4b0d3255bfef95601890afd80709' 
New sha1sum is : '8a826b0c3466fd2a6764d338d29298a39ca60ca1' 



--END OF NOTIFICATION
```

**Comment by youngstar600** [comment]
Can someone please give us an update on this issue?  Thank you so much for your help.

**Comment by youngstar600** [comment]
Please let me know if this issue will be looked at in the near feature.  I think an email alert that shows you what changed would be beneficial to the user.  Ossec does this already.   Again thank you for your help.

**Comment by vikman90** [comment]
Hi @jlruizmlg and @youngstar600

sorry for the delay. I've just fixed this issue: https://github.com/wazuh/wazuh/commit/b333d4f4d02f4663d7a47b2431e9c0f52afa6732

The problem was the order in which the fields appeared within the alert.

From now on, email about FIM alerts will appear this way:

```
To: <wazuh@example.com>
From: Wazuh <ossecm@vmubuntu>
Date: Fri, 13 Oct 2017 21:23:01 -0700
Subject: OSSEC Notification - vmubuntu - Alert level 7


Wazuh Notification.
2017 Oct 13 21:22:46

Received From: vmubuntu->syscheck
Rule: 550 fired (level 7) -> "Integrity checksum changed."
Portion of the log(s):

Integrity checksum changed for: '/root/test/mail.c'
What changed:
22c22
< #include <cstdio>
---
> #include <stdio.h>
Old md5sum was: '709279a9daa57b8a76a27f77341cfdbf'
New md5sum is : '4814556c2e7ab5cbfdd27d4c7f9c33e2'
Old sha1sum was: 'f3f6a78d6e2e087bb68ad978ea7995acded42e82'
New sha1sum is : 'f6e10e1103df088a47502c84820e81ce111ff7cd'
```

Thank you for feedback.
Best regards.

**Comment by youngstar600** [comment]
Thank you!

**Comment by luis-torres** [comment]
Hi Everyone - I donwloaded Wazuh v3.0.0-beta12 and tested the email notification, but I still don't get the details of what changed. Can anyone shed some light please? 

Wazuh Notification.
2017 Nov 15 16:19:13

Received From: (client03) 143.104.38.101->syscheck
Rule: 550 fired (level 7) -> "Integrity checksum changed."
Portion of the log(s):

Integrity checksum changed for: '/backup/test2.txt'
Old md5sum was: '3904ff8cb5cd32968e5f64851eb3bca4'
New md5sum is : '4a2e802fafbbcbb20f0ea9bffa8d3f03'
Old sha1sum was: '097f1e13cc6009655e1e3e8e202561d2b6393b47'
New sha1sum is : '8403d6726b3bfdf7f9e49fc73c944819b06fe39f'

--END OF NOTIFICATION`

**Comment by luis-torres** [comment]
For some strange reason, "what changed" is now displayed in the email alert and working. You can close this thread, Thank you very much for your time.

**Comment by chemamartinez** [comment]
Hi @luis-torres, 

Probably, this issue has happened because the first time that syscheck runs a scan, it saves the data of the files in its Database. 

After that, following scans will be able to check differences in the content of the files and report that changes.

Best regards.

**Comment by vikman90** [comment]
Hi @luis-torres and @chemamartinez,

Let me explain that this data is explicitly dropped in the first scan every time the agent is started. So it isn't exactly a bug, rather a feature.

Perhaps this feature helps to prevent an alert from including too many changes, especially if the agent was stopped for a long time.

This commit removes this feature: https://github.com/wazuh/wazuh/commit/dfd2c435fa77efe5fa84e35f3bd83cd371712b10, but I wonder if this is desirable or beneficial.

I will let the team discuss this, if they approve this commit we will merge it into the next version.

Thanks for reporting!
Best regards.

**Comment by maltfield** [comment]
FYI if you've landed on this issue and the year is closer to 2020 than 2017, you probably want to see this instead:

 * https://github.com/wazuh/wazuh/issues/4919
