### ISSUE TITLE
verify-agent-conf syntax problems with agent.conf

### ISSUE THREAD

**Issue by ghost** [wazuh/wazuh#167]
i have the following in my etc/shared/agents.conf which seem to be correct and was working fine with OSSEC 2.8 (Wazuh), yet it produces errors with latest wazuh-manager (see steps below)

```
<agent_config profile="apache">
    <localfile>
        <location>/var/log/apache2/*.log</location>
        <log_format>apache</log_format>
    </localfile>
</agent_config>


<agent_config profile="bind">
    <localfile>
        <location>/var/log/bind9/*.log</location>
        <log_format>syslog</log_format>
    </localfile>

    <syscheck>
        <directories check_all="yes" report_changes="yes">/var/cache/bind/external,/var/cache/bind/internal</directories>
    </syscheck>
</agent_config>


<agent_config profile="debian">
    <localfile>
        <location>/var/log/cron.log</location>
        <log_format>syslog</log_format>
    </localfile>

    <localfile>
        <location>/var/log/daemon.log</location>
        <log_format>syslog</log_format>
    </localfile>

    <localfile>
        <location>/var/log/debug</location>
        <log_format>syslog</log_format>
    </localfile>

    <localfile>
        <location>/var/log/user.log</location>
        <log_format>syslog</log_format>
    </localfile>
</agent_config>


<agent_config profile="exim">
    <localfile>
        <location>/var/log/exim4/*log</location>
        <log_format>syslog</log_format>
    </localfile>
</agent_config>


<agent_config profile="haproxy">
    <localfile>
        <location>/var/log/haproxy.log</location>
        <log_format>syslog</log_format>
    </localfile>
</agent_config>


<agent_config profile="mysql">
    <localfile>
        <location>/var/log/mysql/error.log</location>
        <log_format>mysql_log</log_format>
    </localfile>
</agent_config>


<agent_config profile="nginx">
    <localfile>
        <location>/var/log/nginx/*.log</location>
        <log_format>apache</log_format>
    </localfile>
</agent_config>
```

1. it doesn't like the wildcard location for apache profile:

> root@test01:/var/ossec# bin/verify-agent-conf
> 
> verify-agent-conf: Verifying [/var/ossec/etc/shared/agent.conf].
> 
> 2017/08/14 12:23:38 verify-agent-conf(1121): ERROR: Glob error. Invalid pattern: '/var/log/apache2/*.log'.
> 2017/08/14 12:23:38 verify-agent-conf(1902): ERROR: Missing 'location' element.
> 2017/08/14 12:23:38 verify-agent-conf(1202): ERROR: Configuration error at '/var/ossec/etc/shared/agent.conf'. Exiting.

ok, i comment the entire apache profile (which as i think is correct) just to verify the file further

2. next step - it doesn't like the wildcard location for bind profile:

> root@test01:/var/ossec# bin/verify-agent-conf
> 
> verify-agent-conf: Verifying [/var/ossec/etc/shared/agent.conf].
> 
> 2017/08/14 12:27:17 verify-agent-conf(1121): ERROR: Glob error. Invalid pattern: '/var/log/bind9/*.log'.
> 2017/08/14 12:27:17 verify-agent-conf(1902): ERROR: Missing 'location' element.
> 2017/08/14 12:27:17 verify-agent-conf(1202): ERROR: Configuration error at '/var/ossec/etc/shared/agent.conf'. Exiting.

ok, i comment this too (i'm still sure it's correct)

3. now the funny part, it seems to pass wildcard location for exim (`*log`) profile but got stuck on nginx (`*.log`):

> root@test01:/var/ossec# bin/verify-agent-conf
> 
> verify-agent-conf: Verifying [/var/ossec/etc/shared/agent.conf].
> 
> 2017/08/14 12:32:06 verify-agent-conf(1121): ERROR: Glob error. Invalid pattern: '/var/log/nginx/*.log'.
> 

but this time the error message doesn't complain about location (as it did for apache and bind profiles) -
 it simply doesn't like the wildcard pattern. i think something is very wrong with this verify-agent-conf tool!

**Comment by naksitrallid** [comment]
some details: OS is Debian 9.1 (Stretch) and Wazuh is 2.0.1-2stretch

**Comment by vikman90** [comment]
Hi @naksitrallid,

this is indeed a bug: the tool `verify-agent-conf` parses the shared file `agent.conf` and checks locally whether locations with wildcard exists in the manager host.

In fact, we are fixing some problems in this program and this is one issue to fix.

Thank you very much for reporting. We'll keep you informed!

Best regards.

**Comment by vikman90** [comment]
Only to confirm, create a folder `/var/log/apache2` in your manager host, and a log file inside it. Then do the same thing with `bind9` and nginx:

```
mkdir -p /var/log/apache2
touch /var/log/apache2/example.log

mkdir -p /var/log/bind9
touch /var/log/bind9/example.log

mkdir -p /var/log/nginx
touch /var/log/nginx/example.log
```

If this works for you we confirm that the issue is that `verify-agent-conf` is checking those files locally. If there is no such `*.log` file in your host, the verification fails.

Thanks.

**Comment by naksitrallid** [comment]
thank you kindly for your reaction. i decided to try it step by step - to display how strange this utility really behaving :)

1. mkdir /var/log/apache2
> root@test01:/var/ossec# bin/verify-agent-conf
> 
> verify-agent-conf: Verifying [/var/ossec/etc/shared/agent.conf].
> 
> 2017/08/16 20:32:19 verify-agent-conf(1121): ERROR: Glob error. Invalid pattern: '/var/log/apache2/*.log'.
> 2017/08/16 20:32:19 verify-agent-conf(1902): ERROR: Missing 'location' element.
> 2017/08/16 20:32:19 verify-agent-conf(1202): ERROR: Configuration error at '/var/ossec/etc/shared/agent.conf'. Exiting.

2. touch /var/log/apache2/example.log

> root@test01:/var/ossec# bin/verify-agent-conf
> 
> verify-agent-conf: Verifying [/var/ossec/etc/shared/agent.conf].
> 
> 2017/08/16 20:33:40 verify-agent-conf(1121): ERROR: Glob error. Invalid pattern: '/var/log/bind9/*.log'.
> 2017/08/16 20:33:40 verify-agent-conf(1121): ERROR: Glob error. Invalid pattern: '/var/log/nginx/*.log'.
3. mkdir /var/log/bind9
> root@test01:/var/ossec# bin/verify-agent-conf
> 
> verify-agent-conf: Verifying [/var/ossec/etc/shared/agent.conf].
> 
> 2017/08/16 20:35:58 verify-agent-conf(1121): ERROR: Glob error. Invalid pattern: '/var/log/bind9/*.log'.
> 2017/08/16 20:35:58 verify-agent-conf(1121): ERROR: Glob error. Invalid pattern: '/var/log/nginx/*.log'.
4. touch /var/log/bind9/example.log
> root@test01:/var/ossec# bin/verify-agent-conf
> 
> verify-agent-conf: Verifying [/var/ossec/etc/shared/agent.conf].
> 
> 2017/08/16 20:36:25 verify-agent-conf(1121): ERROR: Glob error. Invalid pattern: '/var/log/nginx/*.log'.
5. mkdir /var/log/nginx
> root@test01:/var/ossec# bin/verify-agent-conf
> 
> verify-agent-conf: Verifying [/var/ossec/etc/shared/agent.conf].
> 
> 2017/08/16 20:43:19 verify-agent-conf(1121): ERROR: Glob error. Invalid pattern: '/var/log/nginx/*.log'.
6. touch /var/log/nginx/example.log
> root@test01:/var/ossec# bin/verify-agent-conf
> 
> verify-agent-conf: Verifying [/var/ossec/etc/shared/agent.conf].

seems it only complain about missing location (`ERROR: Missing 'location' element`) in the first occurrence only, later it forgets about it and only complaining on invalid pattern instead (doesn't like `*.`?)

i also believe there is no practical use in verifying if log-files exist on wazuh-manager, since this configuration is intended for agents which verify the file/directory existence themselves upon start. i think this tool should only check the agent.conf file structure (if tags are closed and no typos in syntax, if it will comply with the contents of ossec.conf)

**Comment by doubledeee** [comment]
I ran into this bug as well.  It is definitely looking at the local file path on the Manager for verifying the agent conf.  I created a /var/log/httpd/test_access.log, restarted manager (don't know if I had to), and then tried to run the agent-verify and everything checked out.

**Comment by vikman90** [comment]
Hi @doubledeee,

We are working on this issue in this moment, we will keep you updated.

Thanks.

**Comment by mrmqe** [comment]
was this ever solved.. the wildcard is causing this in windows still

**Comment by naksitrallid** [comment]
> @mrmqe 
> was this ever solved.. ?

not in version 2.x i assure you. i had no time to try 3.x yet

**Comment by Zenidd** [comment]
Hello,

The user who opened this issue had two problems with his configuration:

- When using wilcards in Wazuh 2.x, if the path containing wildcard doesn't matches with some file an error is generated. This is fixed from wazuh version 3.6 onwards.

- The locations specified on `agent.conf` were empty on manager host. `verify-agent-conf` checks those files locally.  If there is no such *.log file in the host, the verification fails.
<br></br>
I proceed to close the ticket. If you have any questions or problems again with `verify-agent-conf` do not hesitate to open another ticket.

Regards,

Juan Pablo Sáez

**Comment by MiguelCasaresRobles** [comment]
Hello team,

I observed that this issue is still happening in the latest version 3.13.2. 

After applying the following configuration on the `agent.conf` file:

```
	<syscheck>
		<directories whodata="yes">/export/home/miguel/wildcard/*/wildcard</directories>
		<directories whodata="yes">/export/home/miguel/wildcard/</directories>
	</syscheck>
```

I am getting the following error:

```
 verify-agent-conf: ERROR: (1121): Glob error. Invalid pattern: '/export/home/miguel/wildcard/*/wildcard'.
```

It seems an issue with `verify-agent-conf`. It happens when the agent.conf includes wildcards and the path doesn’t exist in the manager host.

Although is not stopping the manager from sending the centralized configuration to the agent, and I am able to generate the alerts properly, I'd consider this to be a bug.

Let me know if you need anything else from me.

Regards,

Miguel Casares
