### ISSUE TITLE
Ubuntu 22.04 CIS SCA - 5.1.8 and 5.1.9 - Ensure (at | cron) is restricted to authorized users - check fails due to trailing slash (Wazuh events 28632 and 28633)

### ISSUE THREAD

**Issue by gituser28910** [wazuh/wazuh#16907]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.4.1 | Rules/Decoders | New/Error/Improve |

## Description
Same issue in both events 28632 (permissions on /etc/at.allow) and 28633 (permissions on /etc/cron.allow): check tries file "/etc/at.allow/" (and "/etc/cron.allow/" respectively) and fails due to the trailing slash.

### Service/Product/Module
Ubuntu 22.04 CIS SCA

### Current results
Check fails due to trailing slash

### Expected results
Check passes if files exist and have the right permissions

### Proposed fix ("diff original_rules modified_rules"):

```
<       - 'c:stat /etc/cron.allow/ -> r:Access:\s*\t*\(0640/-rw-r-----\)\s*\t*Uid:\s*\t*\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s*\t*\(\s*\t*0/\s*\t*root\)'
---
>       - 'c:stat /etc/cron.allow -> r:Access:\s*\t*\(0640/-rw-r-----\)\s*\t*Uid:\s*\t*\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s*\t*\(\s*\t*0/\s*\t*root\)'

<       - 'c:stat /etc/at.allow/ -> r:Access:\s*\t*\(0640/-rw-r-----\)\s*\t*Uid:\s*\t*\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s*\t*\(\s*\t*0/\s*\t*root\)'
---
>       - 'c:stat /etc/at.allow -> r:Access:\s*\t*\(0640/-rw-r-----\)\s*\t*Uid:\s*\t*\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s*\t*\(\s*\t*0/\s*\t*root\)'
```

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/22dffd3351045ae762d813f8f72de4a8b1d57178

Resolved

**Comment by gituser28910** [comment]
Still not fixed. cis_ubuntu22-04.yml dated August 23 still has trailing slashes for the check. I assume it's the same for the other check (/etc/at.allow).

**Comment by IsExec** [comment]
> Still not fixed. cis_ubuntu22-04.yml dated August 23 still has trailing slashes for the check. I assume it's the same for the other check (/etc/at.allow).

This has been fixed and still undergoing review. It will be merged after the final review
