### ISSUE TITLE
Wazuh agents disconnecting at midnight

### ISSUE THREAD

**Issue by CrazyLlama** [wazuh/wazuh#199]
Hi everyone,

Recently we have upgraded a few legacy agents from OSSEC to Wazuh and we've ran into the same problem with a select few of them disconnecting and spitting out the same 5 error lines:

```
2017/09/21 00:00:00 ossec-agentd: CRITICAL: (1107): Could not create directory '/logs/ossec/2017' due to [(2)-(No such file or directory)].
2017/09/21 00:00:02 ossec-logcollector: ERROR: socketerr (not available).
2017/09/21 00:00:02 ossec-logcollector: ERROR: (1224): Error sending message to queue.
2017/09/21 00:00:05 ossec-logcollector: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2017/09/21 00:00:05 ossec-logcollector: CRITICAL: (1211): Unable to access queue: '/var/ossec/queue/ossec/queue'. Giving up..
```

The disconnection this causes can quickly be fixed by restarting the agent and they connect back straight away. But when midnight is reached again it repeats and comes back to haunt us...

I've just done the following to see if this fixes them tonight or whether the issue re-appears:

```bash
mkdir /var/ossec/logs/ossec
mkdir /var/ossec/logs/ossec/2017
/var/ossec/bin/ossec-control restart
```

Might there be a problem on the management server itself causing this? I know we've previously had issues with the counters and re-adding agents so it may be a cause of manually cleaning up after Wazuh every time we work on it.

Any help is appreciated!

**Comment by CrazyLlama** [comment]
Hi,

Thanks for the pointers, got these as the current permissions:

```
# ls -l /var/ossec | grep logs
drwxr-x--- 3 ossec ossec 4096 Sep 21 10:10 logs

drwxr-xr-x 3 root  root   4096 Sep 21 10:10 ossec
-rw-r----- 1 ossec ossec 59015 Sep 21 12:40 ossec.log
```

So looks like the ossec.log doesn't have the write permissions on the group - I'll update that and post back tomorrow with an update!

**Comment by CrazyLlama** [comment]
Hi All,

Got an update on this - they've gone offline again sadly.

Any other ideas?

**Comment by borbelyau** [comment]
Hi @CrazyLlama ... 
Try to systemctl stop firewalld (if is CentOS)
getenforce (if is CentOS) (change the selinux config to disable)
and
Try
/var/ossec/bin/ossec-logtest -t
and
/var/ossec/bin/ossec-analysisd -df

**Comment by met3or** [comment]
Hi @borbelyau - yes, that folder exists and has the correct permissions: (I am working on this issue alongside @CrazyLlama)

ls -l /var/ossec/queue/ossec/queue
srw-rw---- 1 ossec ossec 0 Sep 25 10:45 /var/ossec/queue/ossec/queue

The agent disconnects each evening at the same time, 00:00:00.

firewalld / iptables are not running at present, and nor is SELinux enabled.  The binaries you're asking to be run, are not present.

Are they available in the Wazuh agent rpm? (which is what we have upgraded to.)

**Comment by borbelyau** [comment]
Check the server that is installed the agent does not have any rule to end the agent

**Comment by borbelyau** [comment]
Are they available in the Wazuh agent rpm? (which is what we have upgraded to.)
What functionality:?

**Comment by met3or** [comment]
@borbelyau - 

> Are they available in the Wazuh agent rpm? (which is what we have upgraded to.)
> What functionality:?

I was referring to the binaries `ossec-logtest` & `ossec-analysisd` which appear to only be provided in the manager, rather than the agent.

> Check the server that is installed the agent does not have any rule to end the agent  

What do you mean, sorry?

**Comment by borbelyau** [comment]
@met3or I dont know if your error is on windows agent, but... that happens if you have any gpo restriction about the time in the application. Or have any AV or FW that blocks traffic in this time...

**Comment by borbelyau** [comment]
The agent that you use... is ossec or wazuh?

**Comment by met3or** [comment]
@borbelyau -  

The environment the agent is installed on is CentOS 7, Wazuh 2.1.0 Agent (as mentioned, upgraded from OSSEC-HIDS 2.8.3).

There are no software restrictions in place, ie. GPO / Firewalld / iptables.  The agent was running fine prior to the update to Wazuh 2.1.0.   

I am having no issues with my agents running on Windows.

**Comment by borbelyau** [comment]
There is no log about the error on your CentOS?

**Comment by borbelyau** [comment]
I found this bro @met3or ...
https://github.com/ossec/ossec-docs/blob/master/docs/faq/unexpected.rst
cannot access /queue/fts/fts-queue. Look for the error message ossec-analysisd(1103): ERROR: Unable to open file '/queue/fts/fts-queue'. This can be fixed by ensuring that the ossec user owns /var/ossec/queue/fts/fts-queue.

**Comment by met3or** [comment]
Hello @borbelyau - Thanks for your help, I'll reset the permissions / ownership on the problematic directories to see if that helps.

I'll feedback later if it has helped.

**Comment by vikman90** [comment]
Hi all,

I've seen that the folder `/var/ossec/logs/ossec` is missing. The process `ossec-agentd` needs it in order to create the folder 2017 inside of it.

Please create it with this permissions:

```
cd /var/ossec/logs
mkdir ossec
chown ossec:ossec ossec
chmod 750 ossec
```

I wonder why this folder has not been create on installing. Hoy did you upgrade the agent?

Hope it help.

**Comment by met3or** [comment]
@vikman90 - Hi,  

We've created that folder now, and set the permissions since working through the thread.   I had upgraded the agent via the method:

`yum install wazuh-agent`

which seemed to pretty seamlessly upgrade ossec-hids to wazuh agent in my tests.

**Comment by vikman90** [comment]
Thank you @met3or,

I'll transmit this issue to the packaging team and they will fix it.

Please let us upgraded if this action fixes the issue tonight.

Best regards.

**Comment by met3or** [comment]
@borbelyau - This issue has now been resolved, the folder /var/ossec/log/ossec was missing from the upgrade.

Once created, and given the correct permissions the agent survives the logrotate at midnight successfully, 

Thanks for all of the help 👍

**Comment by vikman90** [comment]
I'm glad this issue has been fixed!

Let me close the issue.

Best regards.

**Comment by eschipul** [comment]
I have found this error still gets thrown on a clean install (or an upgrade) on ubuntu 14.04 (haven't tested others) if you have not imported the server key on the agent.

`sudo /var/ossec/bin/manage_agents`

**Comment by vikman90** [comment]
Hi @eschipul,

I'm sorry I don't understand your problem. I tried to reproduce the log folder issue on Ubuntu 14.04, it seems that the `/var/ossec/logs/ossec.log` file is created with the correct permissions and the `/var/ossec/logs/ossec` folder exists and has also the proper permissions:

```
-rw-rw---- 1 ossec ossec    0 Sep 19 13:23 active-responses.log
drwxr-x--- 2 ossec ossec 4096 Sep 19 13:23 ossec
-rw-rw---- 1 ossec ossec    0 Nov 15 04:23 ossec.json
-rw-rw---- 1 root  ossec  137 Nov 15 04:25 ossec.log
```

The owner of file `ossec.log` doesn't matter.

Could you confirm that files in your system have the same permissions? If this is not your problem, kindly clarify us the issue you're having.

Kind regards.

**Comment by eschipul** [comment]
@vikman90 - I apologize for my lack of specificity. Of all people, me, I just did that. No excuse. /hangs-head/ Anyway... 

Ubuntu 14.04 or 16.04. Here is what I have found in practice for the agents.  First these are servers that have been upgraded in a large server farm. Endpoints. 

In my last post I did not give the log file locations which is where the misunderstanding occurred (my fault.) I was referring to files located (by default) at:

`/var/log/nginx`

Previously we ran OSSEC agent and switched to wazuh. I purge everything with (yes very redundant code - but servers are much cheaper than humans) like this for an upgrade:

```
sudo apt-get update && \
sudo dpkg --configure -a && \
sudo apt-get update && \
sudo apt-get upgrade && \
sudo apt-get dist-upgrade && \
sudo apt-get clean && \
sudo apt-get autoclean && \
sudo apt-get autoremove
```

Then a complete purge of the old OSSEC agent - I just get tired of guessing and prefer to script it so my team can help.

```
# FORCE REMOVE
sudo su
/var/ossec/bin/ossec-control stop
apt-get remove ossec-hids-agent --purge
rm /var/lib/dpkg/info/wazuh*
rm /etc/init.d/wazuh-agent
rm /etc/apt/sources.list.d/wazuh.list
rm /var/cache/apt/archives/wazuh-agent_2.0.1-1trusty_amd64.deb
rm /var/cache/apt/archives/wazuh-agent_2.1.1-1trusty_amd64.deb
rm /etc/init.d/wazuh-agent
rm -r /var/lib/dpkg/info/wazuh*
rm -rf /var/ossec
rm /etc/init.d/*ossec*
rm /etc/init.d/*wazuh*
deluser ossecm
deluser ossecr
deluser ossec
groupdel ossec
```
I prefer to install from git as opposed to repos given how AWESOME y'all are keeping things up to date. That looks (sort of - I changed it a bit to protect the guilty for this post) like this:

```
sudo apt-get install gcc make git libc6-dev && \
mkdir ossec_tmp && cd ossec_tmp && \
git clone -b stable https://github.com/wazuh/wazuh.git ossec-wazuh && \
cd ossec-wazuh && \
sudo ./install.sh
```

Of course for security the script purges the compilers etc.. different topic. From there because we have a lot of sites I modify the conf file like:

```
# edit this
nano /var/ossec/etc/ossec.conf

  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/nginx/*.log</location>
  </localfile>
```

Then on higher volume endpoints the issue of the ulimit still exists (don't know why, I realize it was patched, but it's there) so I have to then edit the config.

`nano /etc/init.d/wazuh-agent`

and add the one line with "ulimit" - in this case putting the code portion to give it context:

```
start() {
    ulimit -n 10000
    ${DIRECTORY}/bin/ossec-control start
}
```

Then given the purge and reinstall of ossec with wazuh, the key needs to be reimported from the server. Default is:

`sudo /var/ossec/bin/manage_agents`

I'll leave the formal docs to explain that one. Just the "stop" and "start" after importing server-manager key. 

Bottom line - for whatever reason - NGINX log files in `/var/log/nginx` on a legacy server don't always have the correct permissions which prevents the server from reading and moving them over to the ELK stack server for the rest of the team that doesn't like grep.

I do not believe this is a problem with wazuh. I believe it is an issue with legacy OSSEC servers that are converted. I posted it in the hopes of helping others if they hit a similar problem because all of us work too hard to reinvent the wheel. 

Lastly - this bit is your friend if upgrading:

```
chown www-data:adm /var/log/nginx/*
chmod 0640 /var/log/nginx/*.log
```

Whew, and I'm sure there are some errors in there given I was pulling from a script. So for anyone using that code - double check if you need sudo or not. It is COMPLETELY specific to Ubuntu so ymmv on other distros. wazuh with the elastic-stack (formerly ELK) is pretty cool. It's hard to remember that others don't see tail -f like the rest of us. But they don't. So a picture is worth a thousand words as they stay and wazuh with ELK gets you there.

Oh, and then given the "dist-upgrade" you have to reinstall the wazuh plugin to elastic search, restart services, the usual dance.

Thank you @vikman90 for your helpful and insightful comments as this thread helped me. Hopefully my contributions to it will help others. Security rocks!

**Comment by crolopez** [comment]
Hi @eschipul,

As you say, Wazuh doesn't change permissions for files that aren't his own. What has happened to you is very strange, but surely due to the influence of some other software (such as NGINX itself).

Thank you very much for contributing with your suggestions!

Best regards.
