### ISSUE TITLE
Active Response/Command support additional EXPECT fields

### ISSUE THREAD

**Issue by UranusBytes** [wazuh/wazuh#2084]
## Feature request

**Compatibility**
both

**Component involved**
Active Response/Command

Description
--------------
The Active Response Command `expect` option only supports the fields `user`, `srcip`, and `filename`.  It would be powerful to support the mapping of all fields from the event, including dynamically generated fields (from JSON, etc...)

**Comment by vikman90** [comment]
Hi @UranusBytes,

I agree. We introduced `<extra_args>` in 3.5 but this only allows adding static content.

We should extend `<expect>` to accept more fields and dynamic fields.

Let me label this issue as enhancement so we will add it to our roadmap.

We appreciate your feedback.
Best regards.

**Comment by branchnetconsulting** [comment]
May I suggest that it would be perhaps even better to work out a way to pass the entire alert to the active response script as a single JSON record, which is what we are already doing with the integrator system anyway?  That would then give an AR script complete access to the entire alert rather than just to one or more specified fields.

**Comment by iasdeoupxe** [comment]
While reviewing https://github.com/wazuh/wazuh-ruleset/pull/381 i've noticed this issue here.

This also currently means that every json based decoder is also stopping to provide the srcip field to the active response script and thus leaves such products unprotected or am i wrong?

**Comment by iasdeoupxe** [comment]
Adding to the above just allowing more expect fields in the active response commands probably doesn't scale if there are more json based decoders / rules used or even could work unexpectedly:

1. each possible field needs to be known and added there like e.g. the  ``remoteAddr `` of the ownCloud decoder.
2. in the ownCloud decoder case it seems even that the original author hasn't used the  ``remoteAddr `` as the  ``srcip `` but has extracted it from a different field ``message``. It could be possible that this was done on purpose but needs to be verified.

**Comment by jctello** [comment]
Places where the code specifies that these are the only three options:
- [active-response.c](https://github.com/wazuh/wazuh/blob/3.9/src/config/active-response.c#L416)
- [analysisd.c](https://github.com/wazuh/wazuh/blob/3.9/src/analysisd/analysisd.c#L2390)
- [config.c](https://github.com/wazuh/wazuh/blob/3.9/src/analysisd/config.c#L228)
- [exec.c](https://github.com/wazuh/wazuh/blob/3.9/src/analysisd/alerts/exec.c#L33)

Considering that since version 3.8 Windows events are collected via the EventChannel, the field for source IP information in windows is now `win.eventdata.ipAddress`. 
So this affects all Windows systems by default.

**Comment by ssirag** [comment]
Is there any roadmap for this?  Essentially, OSSEC cannot protect my Windows servers right now.

**Comment by Zenidd** [comment]
Hi @ssirag,

this is a really important issue in the AR roadmap. We know that the three supported fields(srcip, user, filename) limitation do not allow to unfold the AR potential. 

We are planning to redesign AR to allow any field, or - as @branchnetconsulting  said above - send the entire alert, and let the scripts parse the needed alert info. We are yet valuing the best option.

In the next weeks, we will introduce the issue in our Sprint planning and we will work out the fix. We look forward to release this feature as soon as possible.

Greetings, JP Sáez

**Comment by jctello** [comment]
Hi @ssirag,

A workaround is to use `eventlog` instead of `eventchannel` for collecting the Security data from your windows agents.
In order to do so edit the `<log_format>` of the configuration of your Windows agent from `eventchannel` to `eventlog` so it looks like this:
```
  <localfile>
    <location>Security</location>
    <log_format>eventlog</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157]</query>
  </localfile>
```
You may change this part of the configuration locally by editing the `C:\Program files (x86)\ossec-agent\ossec.conf` on the agent.

**Comment by ssirag** [comment]
OK; so after I switch eventchannel to eventlog, do I have to do anything else to enable the Windows active response scripts?  The ar.conf file doesn’t reference the nets or route-null commands, which I’ve also added to the agent conf file, and I’m not seeing any recognition in the logs that the script is being called, either correctly or otherwise.

Regards,

Steve Sirag

eResources
O: 800-297-8293 x7034
C: 703-608-8127
eresources.com

**Comment by ssirag** [comment]
Yeah, I reviewed those docs and configured the commands and active response as described, but I’m not seeing it even attempt to call the route-null command, with these settings on the agent:

<command>
    <name>win_route-null-2012</name>
    <executable>route-null-2012.cmd</executable>
    <expect>srcip</expect>
    <timeout_allowed>yes</timeout_allowed>
  </command>

  

  <active-response>
    
    <command>win_route-null-2012</command>
    <location>local</location>
    <level>5</level>
    <timeout>600</timeout>
  </active-response>

Regards,

Steve Sirag

eResources
O: 800-297-8293 x7034
C: 703-608-8127
eresources.com

**Comment by kmfreder1** [comment]
Just curious, is there anything further on this?  This would be a really nice enhancement to Wazuh for anyone in a Windows environment.  The current AR is pretty limiting.

**Comment by vikman90** [comment]
Hi all,

Sorry, we've not been able to address this issue yet. This is a big limitation that particularly affects AR produced from Eventchannel logs.

Moving this issue from the icebox to the product backlog to take into account ASAP.

Thank you for your feedback and patience.
Best regards.

**Comment by upperlimit** [comment]
Is there any new activity on this 2 years old issue, or is abandoned now?

**Comment by vikman90** [comment]
@upperlimit Unfortunately this feature request is still in the icebox. We're facing other issues that have high priority.

We will implement this feature as soon as possible. Thank you for understanding.

Best regards.

**Comment by TomasTurina** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/7317

**Comment by Planokur** [comment]
Hi, I'm on version 4.2.1 and the problem with ar for windows is still present with logformat eventchannel
Here's the logs from agent on windows

`2021/09/15 19:58:23 active-response/bin/netsh.exe: Cannot read 'srcip' from data
2021/09/15 19:58:23 active-response/bin/netsh.exe: Starting
2021/09/15 19:58:23 active-response/bin/netsh.exe: {"version":1,"origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":["IpAddress"],"alert`

More than that if I specify logformat as eventlog I can see the srcip as field but no action ar trigered by ar.

**Comment by branchnetconsulting** [comment]
In Wazuh Manager 4.2.1, we do not need to use `<expect>` any more, unless for backwards compatibility with pre-4.2 Wazuh agents.  The whole alert record is being passed along to ARs now via STDIN.  However the Windows ARs aren't yet adapted to take advantage of the source IP field found in Windows Eventchannel events yet.  See https://github.com/wazuh/wazuh/issues/10022.

**Comment by Planokur** [comment]
I don't use <expect> and the same issue are valid for Nextcloud on Debian 10 I can solve this issue only after I change the log file format on the next cloud setting by adding srcip as one of the variable.
The second issue is that when I move from eventchannel to eventlog I can see srcip as field in Kibana however the active response aren't triggered even by specifying rule id.

**Comment by Sergh71** [comment]
Hi all. I have the same problem. Active-response does not start on Windows via the EventLog. Can you do something to help? Wazuh Manager - App version: 4.3.5; App revision: 4306
Wazuh Agent - 4.3.5

**Comment by ifex380** [comment]
Hi @vikman90 

Can this feature also be extended for the field name "src_ip" ?

Suricata by default has its IP address key name as "src_ip"- https://documentation.wazuh.com/current/learning-wazuh/suricata.html#see-suricata-nids-events-in-the-wazuh-dashboard

Wazuh AR firewalld tries to search for the field name "srcip" from the Suricata log, but it cannot find it since Suricata calls it "src_ip".

Regards,

**Comment by Ifex370** [comment]
Hi @vikman90

Can this feature also be extended for the field name "src_ip" ?

Suricata by default has its IP address key name as "src_ip"- https://documentation.wazuh.com/current/learning-wazuh/suricata.html#see-suricata-nids-events-in-the-wazuh-dashboard

Wazuh AR firewalld tries to search for the field name "srcip" from the Suricata log, but it cannot find it since Suricata calls it "src_ip".

Regards,
