### ISSUE TITLE
Non-UTF8 filename ignored by Wazuh Agent on Windows

### ISSUE THREAD

**Issue by gothren1986** [wazuh/wazuh#28472]
> Hi,
> Still not fixed in 4.11.0 

 _Originally posted by @eandry77 in [#25308](https://github.com/wazuh/wazuh/issues/25308#issuecomment-2700497371)_

**Comment by eandry77** [comment]
Same in France !

**Comment by danl1n** [comment]
Is there anything new with this topic?

**Comment by juliancnn** [comment]
Hi!,

Currently the patch for this issue has been merged in Wazuh v4.12.0

Main issue: https://github.com/wazuh/wazuh/issues/25308
Fix PR: https://github.com/wazuh/wazuh/pull/26289
Comment: https://github.com/wazuh/wazuh/pull/26289#issuecomment-2604211620 the changes have been rescheduled to version 4.12.0.

**Comment by danl1n** [comment]
> Hi!,
> 
> Currently the patch for this issue has been merged in Wazuh v4.12.0
> 
> Main issue: [#25308](https://github.com/wazuh/wazuh/issues/25308) Fix PR: [#26289](https://github.com/wazuh/wazuh/pull/26289) Comment: [#26289 (comment)](https://github.com/wazuh/wazuh/pull/26289#issuecomment-2604211620) rescheduled to version 4.12.0.

Thank you! Do you know when version 4.12 is scheduled to be released public?

**Comment by juliancnn** [comment]
> Thank you! Do you know when version 4.12 is scheduled to be released public?

We have not yet closed 4.12, so we do not have a definite date, we are still working on it.

**Comment by gothren1986** [comment]
Thank you so much! Looking forward to the release 👍

**Comment by JcabreraC** [comment]
As Juli mentioned, this has been resolved in Wazuh v4.12.0.

Closing the issue.

**Comment by juljar** [comment]
Unfortunately, I’ve found that the problem still exists in version 4.12.0.
Any paths containing ä, ö, ü, Ä, Ö, or Ü are being ignored.

Has anyone else observed the same behavior?
