### ISSUE TITLE
Integrate `services` table into Wazuh DB and Inventory Harvester

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#31216]
| Wazuh version | Component(s)               | Install type | Install method   | Platform |
|---------------|----------------------------|--------------|------------------|----------|
| 4.14.0-alpha0 | Wazuh DB, InventoryHarvester | Manager      | Packages/Sources | All      |

## Description

Following the unified ECS-aligned schema for system services, we need to implement support in both **Wazuh DB** and **Inventory Harvester** to handle, store, and index service inventory information across supported platforms.

This data includes system services or daemons installed or running on endpoints and aims to be normalized and queryable across operating systems.

## Functional Requirements

- Implement a unified `services` table aligned with ECS.
- Inventory information must be retrievable via Wazuh's API and CLI.
- Global queries must support filtering and aggregation on this new data.
- The Inventory Harvester must send this data to the indexer.

## Table Structure

The unified table consolidates data from various platform-specific sources (e.g., `systemctl`, `launchctl`, `sc query`, etc.), and aligns it to the [Elastic Common Schema (ECS)](https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html) where applicable.

The proposed schema for this table is detailed in the following comment:  
- [wazuh-agent#807 (comment)](https://github.com/wazuh/wazuh-agent/issues/807#issuecomment-3113217713)

### Wazuh DB

- [x] Implement the `services` table schema in Wazuh DB.
- [ ] Make the data queryable from the Wazuh API and CLI inventory.
- [x] Ensure ECS field naming and relationships are respected.
- [x] Write Unit Tests for the new database logic.

### Inventory Harvester

- [x] Add support to InventoryHarvester to extract and send `services` data.
- [x] Use the field mapping defined in [wazuh-indexer#1055](https://github.com/wazuh/wazuh-indexer/issues/1055).
- [x] Develop and validate Unit Tests.

**Comment by JcabreraC** [comment]
## Update
- Created the first iteration
- Edited `inventoryHarvesterFacade.cpp`
- Added `servicesElement.hpp`
- Review `wcsClassed`

**Comment by JcabreraC** [comment]
## Update:
- Implemented `services` for wazuhDB
- Running tests.

**Comment by JcabreraC** [comment]
## Update:
- WDB completed and tested
- Wazuh-db unit tests completed
- Analyzing global queries

**Comment by JcabreraC** [comment]
Extended ETA

Work on this PR was delayed because the team was focused on other high-priority issues before starting this one.

**Comment by JcabreraC** [comment]
## Update:
- Added services tables
- Implemented inventory harvester development

**Comment by MiguelazoDS** [comment]
# Update 

I'll start revising and fixing UTs

**Comment by JcabreraC** [comment]
## Update
- Fixed missing function `wdb_save`
- Added efficiency test
- Reviewed new fields in `services` for macOS
- Adapted test to new fields

**Comment by MiguelazoDS** [comment]
I've just got the definitive SQL schema. I'll start updating the entire flow for this implementation, following also the indexer schemas.

**Comment by MiguelazoDS** [comment]
I completed the implementation for WDB and global Queries (WIP: The QA efficacy test). 

Team agent mentioned that there's a PK change required due to collision. I still don't know what is the resolution of that. 

I'll stay tuned. I fixes some legacy tests, the logic was ok but the tests were not proven it correctly.

**Comment by JcabreraC** [comment]
## Update:
- Fixed checks
- Corrected branch commits
- Added new field changes for services
- Fixed Unit test

**Comment by MiguelazoDS** [comment]
# Update 

- Updated PK fields based on new requirements. 
- Fixed UTs.

<img width="994" height="357" alt="Image" src="https://github.com/user-attachments/assets/d5367570-f7c9-4eb2-a45f-cef74138b213" />

<img width="1084" height="154" alt="Image" src="https://github.com/user-attachments/assets/a44fe8dd-a06e-412c-83a0-1d4cf9748013" />

Merging local branch with latest changes

**Comment by JcabreraC** [comment]
ETA extended due to new fields added by the agent team and review.

**Comment by MiguelazoDS** [comment]
The discrepancy between indexed documents and data stored in SQLite databases was due to a NULL pk sent by agent. 

After rebase some fixes were added. 

Efficacy 

<img width="1918" height="208" alt="image" src="https://github.com/user-attachments/assets/69d17646-4933-49e7-a0af-c49f434d662e" />

<img width="1122" height="143" alt="Image" src="https://github.com/user-attachments/assets/29e7edfe-5bfa-4fcb-bd13-ca47681ccbcf" />

<img width="1195" height="348" alt="Image" src="https://github.com/user-attachments/assets/53f31687-fc70-4f9b-a413-ed2f5faadf2b" />
