### ISSUE TITLE
CDB list sometimes fail

### ISSUE THREAD

**Issue by elarrarte-d** [wazuh/wazuh#4067]
| 3.10.2 | - | Manager | Packages | Ubuntu 18.04 |

Hi team!

We are having troubles using CDB lists. 

These are the most important rules involved ...
Rule 5715 matches Accepted SSH logins

First, we change the description and rule ID

>     <rule id="106001" level="9">
>         <if_sid>5715</if_sid>
>         <description>High priority linux login audit event</description>
>     </rule>

Then, allowed IPs to make SSH connections are logged as low priority

>     <rule id="105003" level="9">
>         <if_sid>106001</if_sid>
>         <user>root</user>
>         <list field="srcip" lookup="address_match_key">etc/lists/allowedRootLoginIps</list>
>         <description>Low priority linux root login audit event (whitelisted IP)</description>
>     </rule>
> 

Finally, not allowed IPs trigger an alert

>     <rule id="107055" level="10">
>         <if_sid>106001</if_sid>
>         <user>root</user>
>         <list field="srcip" lookup="not_address_match_key">etc/lists/allowedRootLoginIps</list>
>         <description>Critical ssh login with master key</description>
>     </rule>

We 've compiled the list in the master and restart the cluster:
10 managers, +15K VMs

**Test against a whitelisted IP:**

> echo "Oct 10 14:20:04 pp-cassandra-06 sshd[9367]: Accepted publickey for root from 10.1.5.49 port 50944 ssh2: DSA SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" | ossec-logtest
> 2019/10/10 14:20:44 ossec-testrule: INFO: Started (pid: 18584).
> ossec-testrule: Type one log per line.
> 
> **Phase 1: Completed pre-decoding.
>        full event: 'Oct 10 14:20:04 pp-cassandra-06 sshd[9367]: Accepted publickey for root from 10.1.5.49 port 50944 ssh2: DSA SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
>        timestamp: 'Oct 10 14:20:04'
>        hostname: 'pp-cassandra-06'
>        program_name: 'sshd'
>        log: 'Accepted publickey for root from 10.1.5.49 port 50944 ssh2: DSA SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
> 
> **Phase 2: Completed decoding.
>        decoder: 'sshd'
>        dstuser: 'root'
>        srcip: '10.1.5.49'
> 
> **Phase 3: Completed filtering (rules).
>        Rule id: '105003'
>        Level: '9'
>        Description: 'Low priority linux root login audit event (whitelisted IP)'
> **Alert to be generated.

**Test against a not whitelisted IP**

> echo "Oct 10 14:20:04 pp-cassandra-06 sshd[9367]: Accepted publickey for root from 10.2.5.49 port 50944 ssh2: DSA SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" | ossec-logtest
> 2019/10/10 14:22:21 ossec-testrule: INFO: Started (pid: 18978).
> ossec-testrule: Type one log per line.
> 
> **Phase 1: Completed pre-decoding.
>        full event: 'Oct 10 14:20:04 pp-cassandra-06 sshd[9367]: Accepted publickey for root from 10.2.5.49 port 50944 ssh2: DSA SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
>        timestamp: 'Oct 10 14:20:04'
>        hostname: 'pp-cassandra-06'
>        program_name: 'sshd'
>        log: 'Accepted publickey for root from 10.2.5.49 port 50944 ssh2: DSA SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
> 
> **Phase 2: Completed decoding.
>        decoder: 'sshd'
>        dstuser: 'root'
>        srcip: '10.2.5.49'
> 
> **Phase 3: Completed filtering (rules).
>        Rule id: '107055'
>        Level: '10'
>        Description: 'Critical ssh login with master key'
> **Alert to be generated.

Suddenly we get an alert (rule ID 107055) from a whitelisted IP, that 's not right ... immediately check the manager which triggered the alert with the same log, and all is working as expected (rule ID 105003)

Any ideas?

Thanks in advance ...

**Comment by elarrarte-despegar** [comment]
As a workaround we rollback configuration to use <ip> tag and it 's working fine:

> <rule id="107055" level="10">
>     <if_sid>106001</if_sid>
>     <user>root</user>
>     <ip>!X.X.X.X</ip>
>     <ip>!X.X.X.X</ip>
>     <ip>!X.X.X.X</ip>
>     <ip>!X.X.X.X</ip>
>     <description>Critical ssh login with master key</description>
> </rule>

Maybe a bug within CDB subsystem?

**Comment by Lopuiz** [comment]
Hello!

It is due to the cluster doesn't synchronize the ossec.conf file and the workers don't have this list in their configuration.

 To verify I'm right, check if the CDB list is found in the workers. Then you add the list in their configuration.

If it doesn't work, let us know.

Best regards,
Eva

**Comment by elarrarte-despegar** [comment]
Hello Lopuiz!

Yes, we 're using the same list configuration in all our managers.
The ossec.conf file is pushed by a configuration manager (ansible).

When using lists and a false alarm arrives (whitelisted IP), we immediately check the log which triggered the alert against ossec-logtest in the same manager and it 's working as expected -> no alert is triggered

Just one false alarm in a while is triggered, but only when using lists, works perfectly when using <srcip></scrip>

Thanks!

**Comment by elarrarte-despegar** [comment]
Any updates on this?

**Comment by Lopuiz** [comment]
Hello,

Sorry for the late response.

I can't reproduce your case. I have created a CDB list to fire these rules and all seem works correctly in Logtest and Analysisd.

I assume these logs come from `/var/log` and you monitor it using `localfile` tag.

Could you show an example of the CDB list format?

Regards,
Eva

**Comment by elarrarte-d** [comment]
Hi!

Yes, the format of the list is:
> 10.12.13.75:
> 10.70.0.5:
> 10.70.0.6:
> 10.12.5.160:
> 10.12.12.207:
> 10.172.23.113:
> 10.1.5.48:
> 10.1.5.49:
> 10.1.5.50:
> 10.1.5.51:
> 10.70.135.71:
> 10.12.10.207:

We 're matching against the key:
> <rule id="107055" level="10">
>     <if_sid>106001</if_sid>
>     <user>root</user>
>     <list field="srcip" lookup="not_address_match_key">etc/lists/allowedRootLoginIps</list>
>     <description>Critical ssh login with master key</description>
> </rule>

Please, remember that always, always, when testing with ossec-logtest seems to be working fine for us too. We just receive some false alarms during the day. Our automated tests generate a ton of connections from some of those IP addresses, we have around 15k VMs.
But, we never receive false alarms when switching to:
> <rule id="107055" level="10">
>     <if_sid>106001</if_sid>
>     <user>root</user>
>     <srcip>X.X.X.X</srcip>
>     <srcip>X.X.X.X</srcip>
>     <srcip>X.X.X.X</srcip>
>     <srcip>X.X.X.X</srcip>
>     <description>Critical ssh login with master key</description>
> </rule>

Thanks!

**Comment by Lopuiz** [comment]
Hello

I have tested the CDB list and it seems works correctly.
Could you restart the managers again?
It possible the last time they restart didn't have the CDB list because the master didn't send it yet.

If it doesn't work could you tell us which permissions have the CDB list.

Regards,
Eva

**Comment by elarrarte-d** [comment]
Hello!

As I said before, CDB lists are deployed by ansible, the playbook copies the new CDB lists to the master, waits 1 minute for synchronization and then restarts the whole cluster.

Anyways, we 've restarted the cluster and the same thing happens ... 1 false alarm / ton of events of the same kind

Is there anything else we can try/debug?

Thanks!

**Comment by Lopuiz** [comment]
Hello,

You're right. There is a bug in the CDB subsystem. It occurs when some events come at the same time to Analysisd.

I'm sorry for the inconvenience this may cause.
We will solve it as soon as possible.

About debugging Wazuh, it must be compiled in debug mode. IF you have installed using packages you can't use debug mode.

Best regards,
Eva

**Comment by elarrarte-d** [comment]
Hi Lopuiz!

No problem! We are happy to contribute in making Wazuh better.
We 'll be waiting for the patch ...

Regards!

**Comment by elarrarte-d** [comment]
Hi!

Is this bug solved in version 3.11?

Thanks!

**Comment by vikman90** [comment]
@elarrarte-d Apologies, this issue is still in our backlog. I hope to get it in the next sprint and come back to you.

Thank you for your feedback.
Best regards.

**Comment by elarrarte-d** [comment]
OK!

Is there a way to track the advance on this issue after the spring in the case you take it?

Thanks in advance!

**Comment by Zenidd** [comment]
Hello again @elarrarte-d,

sorry for the late reply. We will probably update here our daily/weekly progress as soon as we start working on it. We will take into account your interest!

Best regards, JP Sáez

**Comment by elarrarte-d** [comment]
Thanks!
We 'll be anxiously waiting for progress on this ....

**Comment by elarrarte-d** [comment]
Any updates on this?
Regards!

**Comment by elarrarte-d** [comment]
Hello, it 's been a while ... any updates?

**Comment by joywaves** [comment]
Hi Wazuh team,
by the description, looks similar issue. We bumping up a level to trigger login failure alert where for Windows 2012 it can capture source address and sometimes it may not. 
     
   <field name="win.system.eventID">^4625$</field>
   <list field="win.eventdata.ipAddress" lookup="not_address_match_key">etc/lists/whitelisted_ip</list>
   <description>Windows Logon Failure</description>

In case of Source IP address Not captured by Windows field="win.eventdata.ipAddress" become empty or doesn't exist the rule is failing. Please let me know if this right Issue, if not I'll open new one.

Thank you,
Peter

**Comment by jnasselle** [comment]
Hi @joywaves !

Your problem is also related to this issue. I was able to reproduce it and we are currently working to determinate hoy to solve it.

Sorry for the inconvenience.
Regards,
Nico

**Comment by davidjiglesias** [comment]
Overridden by #11334, the reformat of `wazuh-analysisd` should take care of this issue.

**Comment by pereyra-m** [comment]
Related issue #17026.
