### ISSUE TITLE
Not all alerts.json and archives.json are showing in kibana

### ISSUE THREAD

**Issue by wizardlevel9** [wazuh/wazuh#4409]
VERSION="v3.11.0"
REVISION="31115"
INSTALL="https://packages.wazuh.com/vm/wazuh3.11.0_7.5.1.ova"

I set up suricata as per https://documentation.wazuh.com/3.7/learning-wazuh/suricata.html

The Suricata rule (which i increased to level 10) is being triggered and showing in both alerts.json and archive.json but not showing in kibana and I'm guessing is not being processed correctly in Elastic.

Here is what is shown in /var/ossec/logs/alerts/alerts.json, showing that the rule is firing correctly:

{"timestamp":"2020-01-01T12:20:29.287+0000","rule":{"level":10,"description":"Alert - Test rule or GPL ATTACK_RESPONSE id check returned root","id":"86601","firedtimes":12,"mail":false,"groups":["ids"]},"agent":{"id":"001","name":"DESKTOP-2VFKRJU","ip":"192.168.0.167"},"manager":{"name":"manager"},"id":"1577881229.2348006","decoder":{"name":"json"},"data":{"timestamp":"2020-01-01T23:20:27.286699AUS Eastern Daylight Time","flow_id":"1644931916156833.000000","event_type":"alert","src_ip":"217.160.0.187","src_port":"80","dest_ip":"192.168.0.167","dest_port":"60515","proto":"TCP","app_proto":"http","alert":{"action":"allowed","gid":"1","signature_id":"2100498","rev":"7","signature":"Test rule or GPL ATTACK_RESPONSE id check returned root","category":"Potentially Bad Traffic","severity":"2"}},"location":"\\Program Files\\Titration Security\\Intercept\\log\\intercept.json"}

This indicates to me that the rule is being triggered and processed by Wazuh on the VM, but strangely not being sent/processed by Elastic.

As a reference, when i test the json data in /var/ossec/bin/ossec-logtest it triggers the rule:

**Phase 1: Completed pre-decoding.
       full event: '{"timestamp":"2020-01-01T22:56:27.432212AUS Eastern Daylight Time","flow_id":1754535092223169,"event_type":"alert","src_ip":"217.160.0.187","src_port":80,"dest_ip":"192.168.0.167","dest_port":58860,"proto":"TCP","http":{"hostname":"testmyids.com","url":"\/","http_user_agent":"curl\/7.55.1","http_content_type":"text\/html","http_method":"GET","protocol":"HTTP\/1.1","status":200,"length":39},"app_proto":"http","flow":{"pkts_toserver":4,"pkts_toclient":4,"bytes_toserver":249,"bytes_toclient":470,"start":"2020-01-01T22:56:26.457921AUS Eastern Daylight Time"},"alert":{"action":"allowed","gid":1,"signature_id":2100498,"rev":7,"signature":"Test rule or GPL ATTACK_RESPONSE id check returned root","category":"Potentially Bad Traffic","severity":2}}'
       timestamp: '(null)'
       hostname: 'manager'
       program_name: '(null)'
       log: '{"timestamp":"2020-01-01T22:56:27.432212AUS Eastern Daylight Time","flow_id":1754535092223169,"event_type":"alert","src_ip":"217.160.0.187","src_port":80,"dest_ip":"192.168.0.167","dest_port":58860,"proto":"TCP","http":{"hostname":"testmyids.com","url":"\/","http_user_agent":"curl\/7.55.1","http_content_type":"text\/html","http_method":"GET","protocol":"HTTP\/1.1","status":200,"length":39},"app_proto":"http","flow":{"pkts_toserver":4,"pkts_toclient":4,"bytes_toserver":249,"bytes_toclient":470,"start":"2020-01-01T22:56:26.457921AUS Eastern Daylight Time"},"alert":{"action":"allowed","gid":1,"signature_id":2100498,"rev":7,"signature":"Test rule or GPL ATTACK_RESPONSE id check returned root","category":"Potentially Bad Traffic","severity":2}}'

**Phase 2: Completed decoding.
       decoder: 'json'
       timestamp: '2020-01-01T22:56:27.432212AUS Eastern Daylight Time'
       flow_id: '1754535092223169.000000'
       event_type: 'alert'
       src_ip: '217.160.0.187'
       src_port: '80'
       dest_ip: '192.168.0.167'
       dest_port: '58860'
       proto: 'TCP'
       http.hostname: 'testmyids.com'
       http.url: '/'
       http.http_user_agent: 'curl/7.55.1'
       http.http_content_type: 'text/html'
       http.http_method: 'GET'
       http.protocol: 'HTTP/1.1'
       http.status: '200'
       http.length: '39'
       app_proto: 'http'
       flow.pkts_toserver: '4'
       flow.pkts_toclient: '4'
       flow.bytes_toserver: '249'
       flow.bytes_toclient: '470'
       flow.start: '2020-01-01T22:56:26.457921AUS Eastern Daylight Time'
       alert.action: 'allowed'
       alert.gid: '1'
       alert.signature_id: '2100498'
       alert.rev: '7'
       alert.signature: 'Test rule or GPL ATTACK_RESPONSE id check returned root'
       alert.category: 'Potentially Bad Traffic'
       alert.severity: '2'

**Phase 3: Completed filtering (rules).
       Rule id: '86601'
       Level: '10'
       Description: 'Alert - Test rule or GPL ATTACK_RESPONSE id check returned root'
**Alert to be generated.

Can you please help me fix this issue. Thanks in advance.

**Comment by wizardlevel9** [comment]
As you can see from the output of var/ossec/bin/ossec-logtest, I have changed the rule level from 10 to 9 to 3, to see if that changes anything. In fact, I have tried so many combinations and permutations that I'm at a loss to understand what is going on.

**Comment by pablotr9** [comment]
Hi @wizardlevel9 ,

If the alert is in the **alerts.json** file (/var/ossec/logs/alerts/alerts.json), as you say the alert is correctly triggered in your Wazuh server and the problem is in the communication with Elasticsearch, I will need some more information to give you further assistance:

Are you using Filebeat or Logstash? Could you please attach the configuration file? 
Filebeat `/etc/filebeat/filebeat.yml`
Logstash `/etc/logstash/conf.d/01-wazuh.conf`

Could you please attach your Elasticsearch log file? You can find this log file in `/var/log/elasticsearch/(clusterName/elasticsearch).log `
Replace clusterName/elasticsearch with the name of your cluster or with `elasticsearch` if no name is specified.

Best regard,
Pablo Torres

**Comment by wizardlevel9** [comment]
Hi Pablo,
You were right. I found the error in the elastic logs. Here it is:
"Caused by: java.lang.IllegalArgumentException: failed to parse date field [2020-01-03T20:16:32.550042AUS Eastern Daylight Time] with format [strict_date_optional_time||epoch_millis]",

The issue I have is that I can't change the logging in the application which has it's timestamp to include timezone eg "AUS Eastern Daylight Time"

Is there a mapping i can apply in elasticsearch to accept this?

Thanks once again.

**Comment by wizardlevel9** [comment]
It looks like this part of the json (from my first posting above) is causing the issue.

"data":{"timestamp":"2020-01-01T23:20:27.286699AUS Eastern Daylight Time"

Any guidance on how i can make elastic accept and process the data.timestamp with my timezone would be greatly appreciated.

Thanks again Pablo

**Comment by pablotr9** [comment]
Hi @wizardlevel9 ,

You are right, your timestamp can't be parsed correctly by Elasticsearch, it looks like the timezone `AUS Eastern Daylight Time` is not recognized correctly (the expected timezone identity format should be something like Australia/Sydney (or +10:00 / +1000) more info [here](http://joda-time.sourceforge.net/timezones.html)) 
One solution should be specifying the date format in the logging application to a compatible format with Elasticsearch.

If that's not possible, you may also want to check the **Date filter plugin** which is used for parsing dates from fields. You can find more information about this filter in the Elastic docs: https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html. There you can find the syntax to parse the date.

Another solution, which I have just tested and it's working as expected with the timestamp you sent me (2020-01-01T23:20:27.286699AUS Eastern Daylight Time), is a **ruby filter** in your Logstash configuration to remove the `AUS Eastern Daylight Time` text from your timestamp. I personally do **not** recommend using this option in some cases, as it can be less efficient than other alternatives and the timezone information is being lost, but it can be temporarily used to do not lose any alert in your server while another solution is found. Using it or not will depend on your needs.
If you are interested in this workaround to make it work, edit your Logstash configuration (/etc/logstash/conf.d/01-wazuh.conf) and after the filter JSON add this block of code: 
```
filter {
    ruby {
      code => "if event.get('timestamp').match(/AUS Eastern Daylight Time/)
                event.set('timestamp',event.get('timestamp')[0..-28])
        end"
    }
}
```
As I said, the best option should be parsing the date correctly using the [date filter plugin](https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html).

I will try to give you another solution as soon as possible, let me know if it helps or if you find any other alternative to solve it!

Kind regards,
Pablo Torres

**Comment by wizardlevel9** [comment]
Thanks Pablo. I'll give it a try and let you know how i go.

Thank you so much for helping me out and for finding so many ways to solve this. More importantly, thanks for testing it and providing me with very clear instructions on finding the issue and how to work around it.

I'll keep you posted on how i go.

**Comment by wizardlevel9** [comment]
Hi Pablo, I looked at my setup and since i am using a new version of the VM, it does not contain logstash. The current versions on use Filebeat.
Do you recommend that I install logstash in order to parse the date?
If so, can you recommend how i should make the changes to Filebeat in order for it to cooperate with Logstash if I was to install it.
Thanks again.

**Comment by pablotr9** [comment]
Hi @wizardlevel9 ,

Ok, sorry, I thought you were using Logstash. Logstash can be installed but I recommend using just Filebeat for this case, you will only have to edit the ingest pipeline of our Wazuh module, I'll explain to you how to do it:
1. Stop Filebeat 
`systemctl stop filebeat`
2. Delete the current pipeline from your Elasticsearch (You can do all these requests in the Kibana Dev Tools tab)
    - List ingest pipelines:
          `GET _ingest/pipeline`     
             Then you will have to find the Wazuh alerts pipeline, it should be called something like **filebeat-7.5.1-wazuh-alerts-pipeline** (the name will vary depending on the Filebeat version)
     - Remove the pipeline:
         `DELETE _ingest/pipeline/filebeat-7.5.1-wazuh-alerts-pipeline`
3. Edit the Wazuh module pipeline, you can find this file here:  **/usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json** and replace its content with the `pipeline.json` you can find in this **.zip**: [pipeline.zip](https://github.com/wazuh/wazuh/files/4029743/pipeline.zip)
You can see that the only difference of that pipeline with the default pipeline is a new `gsub` processor:

**Comment by wizardlevel9** [comment]
Hi Pablo,
I followed your instructions and update the file (with the correct starting and stopping of processes) and I'm still getting the same error.

I even rebooted the machine just in case, but it appears that the 'gsub' isn't doing what it is supposed to. I'm still getting the same error in elastic:

"Caused by: java.lang.IllegalArgumentException: failed to parse date field [2020-01-08T00:46:39.001805AUS Eastern Daylight Time] with format [strict_date_optional_time||epoch_millis]",

Thanks in advance.

**Comment by pablotr9** [comment]
Hi @wizardlevel9 ,

Ok let's see what is happening, could you please share with me the output of this command:
`GET _ingest/pipeline`

Could you also send me that specific alert so I can test it on my server? 
`cat /var/ossec/logs/alerts/alerts.json | grep "2020-01-08T00:46:39.001805AUS Eastern Daylight Time"`

Best regards,
Pablo Torres

**Comment by wizardlevel9** [comment]
{
  "filebeat-7.5.1-wazuh-alerts-pipeline" : {
    "on_failure" : [
      {
        "drop" : { }
      }
    ],
    "description" : "Wazuh alerts pipeline",
    "processors" : [
      {
        "json" : {
          "add_to_root" : true,
          "field" : "message"
        }
      },
      {
        "geoip" : {
          "ignore_failure" : true,
          "field" : "data.srcip",
          "target_field" : "GeoLocation",
          "properties" : [
            "city_name",
            "country_name",
            "region_name",
            "location"
          ],
          "ignore_missing" : true
        }
      },
      {
        "geoip" : {
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "data.win.eventdata.ipAddress",
          "target_field" : "GeoLocation",
          "properties" : [
            "city_name",
            "country_name",
            "region_name",
            "location"
          ]
        }
      },
      {
        "geoip" : {
          "ignore_failure" : true,
          "field" : "data.aws.sourceIPAddress",
          "target_field" : "GeoLocation",
          "properties" : [
            "city_name",
            "country_name",
            "region_name",
            "location"
          ],
          "ignore_missing" : true
        }
      },
      {
        "date" : {
          "field" : "timestamp",
          "target_field" : "@timestamp",
          "formats" : [
            "ISO8601"
          ],
          "ignore_failure" : false
        }
      },
      {
        "date_index_name" : {
          "field" : "timestamp",
          "date_rounding" : "d",
          "index_name_prefix" : "{{fields.index_prefix}}",
          "index_name_format" : "yyyy.MM.dd",
          "ignore_failure" : false
        }
      },
      {
        "remove" : {
          "field" : "message",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "ecs"
        }
      },
      {
        "remove" : {
          "field" : "beat",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "input_type",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "tags",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "count",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "ignore_failure" : true,
          "field" : "@version",
          "ignore_missing" : true
        }
      },
      {
        "remove" : {
          "field" : "log",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "offset",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "type"
        }
      },
      {
        "remove" : {
          "field" : "host",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "ignore_failure" : true,
          "field" : "fields",
          "ignore_missing" : true
        }
      },
      {
        "remove" : {
          "field" : "event",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "fileset",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "service",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      }
    ]
  },
  "xpack_monitoring_6" : {
    "description" : "This pipeline upgrades documents from the older version of the Monitoring API to the newer version (7) by fixing breaking changes in those older documents before they are indexed from the older version (6).",
    "version" : 7000199,
    "processors" : [
      {
        "script" : {
          "source" : "ctx._type = null"
        }
      },
      {
        "gsub" : {
          "field" : "_index",
          "pattern" : """(.monitoring-\w+-)6(-.+)""",
          "replacement" : "$17$2"
        }
      }
    ]
  },
  "filebeat-7.5.1-wazuh-archives-pipeline" : {
    "description" : "Wazuh events pipeline",
    "processors" : [
      {
        "json" : {
          "field" : "message",
          "add_to_root" : true
        }
      },
      {
        "geoip" : {
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "data.srcip",
          "target_field" : "GeoLocation",
          "properties" : [
            "city_name",
            "country_name",
            "region_name",
            "location"
          ]
        }
      },
      {
        "geoip" : {
          "properties" : [
            "city_name",
            "country_name",
            "region_name",
            "location"
          ],
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "data.win.eventdata.ipAddress",
          "target_field" : "GeoLocation"
        }
      },
      {
        "geoip" : {
          "field" : "data.aws.sourceIPAddress",
          "target_field" : "GeoLocation",
          "properties" : [
            "city_name",
            "country_name",
            "region_name",
            "location"
          ],
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "date" : {
          "formats" : [
            "ISO8601"
          ],
          "ignore_failure" : false,
          "field" : "timestamp",
          "target_field" : "@timestamp"
        }
      },
      {
        "date_index_name" : {
          "field" : "timestamp",
          "date_rounding" : "d",
          "index_name_prefix" : "{{fields.index_prefix}}",
          "index_name_format" : "yyyy.MM.dd",
          "ignore_failure" : false
        }
      },
      {
        "remove" : {
          "ignore_failure" : true,
          "field" : "message",
          "ignore_missing" : true
        }
      },
      {
        "remove" : {
          "field" : "ecs",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "beat",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "input_type",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "tags"
        }
      },
      {
        "remove" : {
          "field" : "count",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "@version",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "log",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "offset",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "type",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "host"
        }
      },
      {
        "remove" : {
          "field" : "fields",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "event",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "fileset",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "ignore_failure" : true,
          "field" : "service",
          "ignore_missing" : true
        }
      }
    ],
    "on_failure" : [
      {
        "drop" : { }
      }
    ]
  },
  "xpack_monitoring_7" : {
    "description" : "This is a placeholder pipeline for Monitoring API version 7 so that future versions may fix breaking changes.",
    "version" : 7000199,
    "processors" : [ ]
  }
}

With the command -> cat /var/ossec/logs/alerts/alerts.json | grep "2020-01-08T00:46:39.001805AUS Eastern Daylight Time"
I didn't get anything back with that exact grep, but here is the closest I found in alerts.json:

{"timestamp":"2020-01-07T13:46:30.376+0000","rule":{"level":9,"description":"Alert - Test Rule or GPL ATTACK_RESPONSE id check returned root","id":"86601","firedtimes":6,"mail":false,"groups":["ids"]},"agent":{"id":"001","name":"DESKTOP-2VFKRJU","ip":"192.168.0.167"},"manager":{"name":"manager"},"id":"1578404790.474487","decoder":{"name":"json"},"data":{"timestamp":"2020-01-08T00:46:27.480550AUS Eastern Daylight Time","flow_id":"1573802915037532.000000","event_type":"alert","src_ip":"217.160.0.187","src_port":"80","dest_ip":"192.168.0.167","dest_port":"59056","proto":"TCP","alert":{"action":"allowed","gid":"1","signature_id":"1","rev":"7","signature":"Test Rule or GPL ATTACK_RESPONSE id check returned root","category":"Potentially Bad Traffic","severity":"2"},"app_proto":"http"},"location":"\\Program Files\\Titration Security\\Intercept\\log\\intercept.json"}

{"timestamp":"2020-01-07T13:46:30.408+0000","rule":{"level":9,"description":"Alert - Test rule or GPL ATTACK_RESPONSE id check returned root","id":"86601","firedtimes":7,"mail":false,"groups":["ids"]},"agent":{"id":"001","name":"DESKTOP-2VFKRJU","ip":"192.168.0.167"},"manager":{"name":"manager"},"id":"1578404790.475567","decoder":{"name":"json"},"data":{"timestamp":"2020-01-08T00:46:27.480550AUS Eastern Daylight Time","flow_id":"1573802915037532.000000","event_type":"alert","src_ip":"217.160.0.187","src_port":"80","dest_ip":"192.168.0.167","dest_port":"59056","proto":"TCP","app_proto":"http","alert":{"action":"allowed","gid":"1","signature_id":"2100498","rev":"7","signature":"Test rule or GPL ATTACK_RESPONSE id check returned root","category":"Potentially Bad Traffic","severity":"2"}},"location":"\\Program Files\\Titration Security\\Intercept\\log\\intercept.json"}

**Comment by pablotr9** [comment]
Hi @wizardlevel9 ,

I can see that your ingest pipeline is not updated, maybe you missed one of the steps.

Let's try removing your ingest pipeline: 
`DELETE _ingest/pipeline/filebeat-7.5.1-wazuh-alerts-pipeline`

Now restart Filebeat:
`systemctl restart filebeat` 

Please check if you are still getting that error, in that case please attach to your reply the content of this file:
`cat /usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json`

Best regards,
Pablo Torres

**Comment by wizardlevel9** [comment]
Sorry for being a pain Pablo but I'm still getting the same error in elastic.

GET _ingest/pipeline
{
  "filebeat-7.5.1-wazuh-alerts-pipeline" : {
    "on_failure" : [
      {
        "set" : {
          "field" : "ferror",
          "value" : "failed-{{ _ingest.on_failure_message }}"
        }
      }
    ],
    "description" : "Wazuh alerts pipeline",
    "processors" : [
      {
        "json" : {
          "add_to_root" : true,
          "field" : "message"
        }
      },
      {
        "geoip" : {
          "target_field" : "GeoLocation",
          "properties" : [
            "city_name",
            "country_name",
            "region_name",
            "location"
          ],
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "data.srcip"
        }
      },
      {
        "gsub" : {
          "replacement" : "Z",
          "on_failure" : [
            {
              "set" : {
                "value" : "failed-{{ _ingest.on_failure_message }}",
                "field" : "timestamperror"
              }
            }
          ],
          "field" : "timestamp",
          "pattern" : "...AUS Eastern Daylight Time"
        }
      },
      {
        "geoip" : {
          "field" : "data.win.eventdata.ipAddress",
          "target_field" : "GeoLocation",
          "properties" : [
            "city_name",
            "country_name",
            "region_name",
            "location"
          ],
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "geoip" : {
          "field" : "data.aws.sourceIPAddress",
          "target_field" : "GeoLocation",
          "properties" : [
            "city_name",
            "country_name",
            "region_name",
            "location"
          ],
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "date" : {
          "field" : "timestamp",
          "target_field" : "@timestamp",
          "formats" : [
            "ISO8601"
          ],
          "ignore_failure" : false
        }
      },
      {
        "date_index_name" : {
          "date_rounding" : "d",
          "index_name_prefix" : "{{fields.index_prefix}}",
          "index_name_format" : "yyyy.MM.dd",
          "ignore_failure" : false,
          "field" : "timestamp"
        }
      },
      {
        "remove" : {
          "field" : "message",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "ecs",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "beat",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "ignore_failure" : true,
          "field" : "input_type",
          "ignore_missing" : true
        }
      },
      {
        "remove" : {
          "field" : "tags",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "count",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "@version",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "log",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "offset",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "type",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "host",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "fields",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "event"
        }
      },
      {
        "remove" : {
          "field" : "fileset",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "service",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      }
    ]
  },
  "xpack_monitoring_6" : {
    "description" : "This pipeline upgrades documents from the older version of the Monitoring API to the newer version (7) by fixing breaking changes in those older documents before they are indexed from the older version (6).",
    "version" : 7000199,
    "processors" : [
      {
        "script" : {
          "source" : "ctx._type = null"
        }
      },
      {
        "gsub" : {
          "field" : "_index",
          "pattern" : """(.monitoring-\w+-)6(-.+)""",
          "replacement" : "$17$2"
        }
      }
    ]
  },
  "filebeat-7.5.1-wazuh-archives-pipeline" : {
    "description" : "Wazuh events pipeline",
    "processors" : [
      {
        "json" : {
          "field" : "message",
          "add_to_root" : true
        }
      },
      {
        "geoip" : {
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "data.srcip",
          "target_field" : "GeoLocation",
          "properties" : [
            "city_name",
            "country_name",
            "region_name",
            "location"
          ]
        }
      },
      {
        "geoip" : {
          "properties" : [
            "city_name",
            "country_name",
            "region_name",
            "location"
          ],
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "data.win.eventdata.ipAddress",
          "target_field" : "GeoLocation"
        }
      },
      {
        "geoip" : {
          "field" : "data.aws.sourceIPAddress",
          "target_field" : "GeoLocation",
          "properties" : [
            "city_name",
            "country_name",
            "region_name",
            "location"
          ],
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "date" : {
          "formats" : [
            "ISO8601"
          ],
          "ignore_failure" : false,
          "field" : "timestamp",
          "target_field" : "@timestamp"
        }
      },
      {
        "date_index_name" : {
          "field" : "timestamp",
          "date_rounding" : "d",
          "index_name_prefix" : "{{fields.index_prefix}}",
          "index_name_format" : "yyyy.MM.dd",
          "ignore_failure" : false
        }
      },
      {
        "remove" : {
          "ignore_failure" : true,
          "field" : "message",
          "ignore_missing" : true
        }
      },
      {
        "remove" : {
          "field" : "ecs",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "beat",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "input_type",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "tags"
        }
      },
      {
        "remove" : {
          "field" : "count",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "@version",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "log",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "offset",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "type",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "ignore_missing" : true,
          "ignore_failure" : true,
          "field" : "host"
        }
      },
      {
        "remove" : {
          "field" : "fields",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "event",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "fileset",
          "ignore_missing" : true,
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "ignore_failure" : true,
          "field" : "service",
          "ignore_missing" : true
        }
      }
    ],
    "on_failure" : [
      {
        "drop" : { }
      }
    ]
  },
  "xpack_monitoring_7" : {
    "description" : "This is a placeholder pipeline for Monitoring API version 7 so that future versions may fix breaking changes.",
    "version" : 7000199,
    "processors" : [ ]
  }
}

[root@manager ~]# cat /usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json
{
  "description": "Wazuh alerts pipeline",
  "processors": [
    { "json" : { "field" : "message", "add_to_root": true } },
    {
      "geoip": {
        "field": "data.srcip",
        "target_field": "GeoLocation",
        "properties": ["city_name", "country_name", "region_name", "location"],
        "ignore_missing": true,
        "ignore_failure": true
      }
    },
{
  "gsub": {
    "field": "timestamp",
    "pattern": "...AUS Eastern Daylight Time",
    "replacement": "Z",
    "on_failure" : [
     {
       "set" : {
         "field" : "timestamperror",
         "value" : "failed-{{ _ingest.on_failure_message }}"
       }
     }
   ]
  }
},
    {
      "geoip": {
        "field": "data.win.eventdata.ipAddress",
        "target_field": "GeoLocation",
        "properties": ["city_name", "country_name", "region_name", "location"],
        "ignore_missing": true,
        "ignore_failure": true
      }
    },
    {
      "geoip": {
        "field": "data.aws.sourceIPAddress",
        "target_field": "GeoLocation",
        "properties": ["city_name", "country_name", "region_name", "location"],
        "ignore_missing": true,
        "ignore_failure": true
      }
    },
    {
      "date": {
        "field": "timestamp",
        "target_field": "@timestamp",
        "formats": ["ISO8601"],
        "ignore_failure": false
      }
    },
    {
      "date_index_name": {
        "field": "timestamp",
        "date_rounding": "d",
        "index_name_prefix": "{{fields.index_prefix}}",
        "index_name_format": "yyyy.MM.dd",
        "ignore_failure": false 
      }
    },
    { "remove": { "field": "message", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "ecs", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "beat", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "input_type", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "tags", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "count", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "@version", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "log", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "offset", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "type", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "host", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "fields", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "event", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "fileset", "ignore_missing": true, "ignore_failure": true } },
    { "remove": { "field": "service", "ignore_missing": true, "ignore_failure": true } }
  ],
 "on_failure" : [
    {
      "set" : {
        "field" : "ferror",
        "value" : "failed-{{ _ingest.on_failure_message }}"
      }
    }
  ]
}

**Comment by pablotr9** [comment]
Hi @wizardlevel9 ,

Don't worry, we are here to help! The pipeline looks good now, so it has been updated successfully, let's restart again. It should be working fine, please share with me the full error log (check the timestamp of the error log) and also check in Kibana Discover that there are alerts according to the time range.

Best regards,
Pablo Torres

**Comment by wizardlevel9** [comment]
Hi Pablo,

I restarted and then rebooted (just to make double sure) but nothing is showing up in Kibana Discover.

Here is the error from elastic:
"at java.lang.Thread.run(Thread.java:830) [?:?]",
"Caused by: java.lang.IllegalArgumentException: failed to parse date field [2020-01-08T02:02:14.274540AUS Eastern Daylight Time] with format [strict_date_optional_time||epoch_millis]",
"at org.elasticsearch.common.time.JavaDateFormatter.parse(JavaDateFormatter.java:169) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.index.mapper.DateFieldMapper$DateFieldType.parse(DateFieldMapper.java:338) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.index.mapper.DateFieldMapper.parseCreateField(DateFieldMapper.java:545) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:277) ~[elasticsearch-7.5.1.jar:7.5.1]",
"... 44 more",

[root@manager ~]# cat /var/ossec/logs/alerts/alerts.json | grep "2020-01-08T02:02:14.274540AUS"
{"timestamp":"2020-01-07T15:02:17.837+0000","rule":{"level":9,"description":"Alert - Test Rule or GPL ATTACK_RESPONSE id check returned root","id":"86601","firedtimes":7,"mail":false,"groups":["ids"]},"agent":{"id":"001","name":"DESKTOP-2VFKRJU","ip":"192.168.0.167"},"manager":{"name":"manager"},"id":"1578409337.639076","decoder":{"name":"json"},"data":{"timestamp":"2020-01-08T02:02:14.274540AUS Eastern Daylight Time","flow_id":"827213342907440.000000","event_type":"alert","src_ip":"217.160.0.187","src_port":"80","dest_ip":"192.168.0.167","dest_port":"61019","proto":"TCP","alert":{"action":"allowed","gid":"1","signature_id":"1","rev":"7","signature":"Test Rule or GPL ATTACK_RESPONSE id check returned root","category":"Potentially Bad Traffic","severity":"2"},"app_proto":"http"},"location":"\\Program Files\\Titration Security\\Intercept\\log\\intercept.json"}

{"timestamp":"2020-01-07T15:02:17.854+0000","rule":{"level":9,"description":"Alert - Test rule or GPL ATTACK_RESPONSE id check returned root","id":"86601","firedtimes":8,"mail":false,"groups":["ids"]},"agent":{"id":"001","name":"DESKTOP-2VFKRJU","ip":"192.168.0.167"},"manager":{"name":"manager"},"id":"1578409337.640154","decoder":{"name":"json"},"data":{"timestamp":"2020-01-08T02:02:14.274540AUS Eastern Daylight Time","flow_id":"827213342907440.000000","event_type":"alert","src_ip":"217.160.0.187","src_port":"80","dest_ip":"192.168.0.167","dest_port":"61019","proto":"TCP","app_proto":"http","alert":{"action":"allowed","gid":"1","signature_id":"2100498","rev":"7","signature":"Test rule or GPL ATTACK_RESPONSE id check returned root","category":"Potentially Bad Traffic","severity":"2"}},"location":"\\Program Files\\Titration Security\\Intercept\\log\\intercept.json"}

**Comment by pablotr9** [comment]
Hi @wizardlevel9 ,

Ok, I just found where is the error, we fixed the parsing error in the field `timestamp` but there is another timestamp in the field `data.timestamp` which is causing the same error, so we have to remove the `AUS Eastern Daylight Time` text from that field too.
Let's do again these steps:
1. Stop Filebeat
`systemctl stop filebeat`
2. Remove the current pipeline.
`DELETE _ingest/pipeline/filebeat-7.5.1-wazuh-alerts-pipeline`
3. Replace the file **/usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json** with this file: 
[pipeline.zip](https://github.com/wazuh/wazuh/files/4031305/pipeline.zip)
4. Restart Filebeat
`systemctl restart filebeat`

Let me know if you are still receiving that `failed to parse date field` error or any other error.


Best regards,
Pablo Torres

**Comment by wizardlevel9** [comment]
Hi Pablo,

The gsub for data.timestamp did the trick!

I can now see the alerts in Kibana. I'm still seeing same the error in Elastic, but the alerts are showing in Kibana, which is what i wanted.

Thank you so much for your help. You are a legend.

**Comment by pablotr9** [comment]
Hi @wizardlevel9 ,

I'm glad it works! I will close this issue, feel free to reopen it or open a new issue if you have any feature request or bug report. If I found any other solution I will let you know.
If you need help or have any questions, please join our mailing list or our Slack channel. More info can be found [here](https://wazuh.com/community/).

Kind Regards,
Pablo Torres
