### ISSUE TITLE
Restarting Windows agent from the manager does not work

### ISSUE THREAD

**Issue by odintree** [wazuh/wazuh#5196]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|3.12.x|-|Agent|Packages|Windows|

Hi team, 
Detected a bug with restarting the Windows `agent` from the `Manager`. 

Tested with a command: `/var/ossec/bin/agent_control -R -u 001`. 
Also, tried to restart it using API: `curl -u foo:bar -k -X PUT "https://127.0.0.1:55000/agents/001/restart?pretty"`. 
Both of the methods do not restart the Windows agent. 
In the Windows log there is an info message: 
`Active response command not present: 'active-response/bin/restart-ossec.sh'. Not using it on this system.`
This bug is applied to Windows only. There are no issues with restarting Linux agents. 

_Workaround:_ 

It is needed to add to a file /var/ossec/etc/ossec.conf
```
 <command>
    <name>restart-ossec-win</name>
    <executable>restart-ossec.cmd</executable>
    <expect/>
 </command>
```
and
```
<active-response>
  <command>restart-ossec-win</command>
  <location>local</location>
</active-response>
```

And trigger the `command` with:  
`curl -u foo:bar -k -X PUT -d '{"command":"restart-ossec-win0", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"]}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/001?pretty"`

Also, changing the agent's centralized configuration will also perform a proper restart.

Kind regards,
Do Tuan Anh.

**Comment by jlruizmlg** [comment]
+1 same here

**Comment by 0xN3utr0n** [comment]
Hi guys,
Thanks for everyone's feedback. There was a small typo when generating the `ar.conf` file, an unexpected space before the windows command which made the line invalid.
The issue has been fixed in #5212.

kind regards

**Comment by mark260486** [comment]
Hello, @0xN3utr0n!

It seems that this fix does not solve our problem. ```ar.conf``` was fixed by ourselves. Could you advise, please?

**Comment by 0xN3utr0n** [comment]
Hi @mark260486 ,
The PR I made fixed only the typo in `ar.conf` which was causing the issue commented by @odintree. Your problem seems to be a completely different and unrelated one, so you should open a new Issue explaining how to replicate your scenario, what fails, Wazuh versions, configuration, and so on... 

kind regards,
Fernando

**Comment by mark260486** [comment]
I will. Thank you very much.
